export const characters = [{ 
	name: "albedo",
	element: "geo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Topaz Sliver", value: 0 },
			threeStar: { item: "Topaz Fragment", value: 0 },
			fourStar: { item: "Topaz Chunk", value: 0 },
			fiveStar: { item: "Topaz Gemstone", value: 0 },
		},
		boss: { item: "Basalt Pillar", value: 0 },
		common: {
			oneStar: { item: "Divining Scroll", value: 0 },
			twoStar: { item: "Sealed Scroll", value: 0 },
			threeStar: { item: "Forbidden Scroll", value: 0 },
		},
		region: { item: "Cecilia", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Tusk of Monoceros Caeli", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Divining Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sealed Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Forbidden Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "aloy",
	element: "cryo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Jade Sliver", value: 0 },
			threeStar: { item: "Jade Fragment", value: 0 },
			fourStar: { item: "Jade Chunk", value: 0 },
			fiveStar: { item: "Jade Gemstone", value: 0 },
		},
		boss: { item: "Crystalline Bloom", value: 0 },
		common: {
			oneStar: { item: "Spectral Husk", value: 0 },
			twoStar: { item: "Spectral Heart", value: 0 },
			threeStar: { item: "Spectral Nucleus", value: 0 },
		},
		region: { item: "Crystal Marrow", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Molten Moment", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Spectral Husk", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Spectral Heart", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Spectral Nucleus", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "amber",
	element: "pyro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Agate Sliver", value: 0 },
			threeStar: { item: "Agate Fragment", value: 0 },
			fourStar: { item: "Agate Chunk", value: 0 },
			fiveStar: { item: "Agate Gemstone", value: 0 },
		},
		boss: { item: "Everflame Seed", value: 0 },
		common: {
			oneStar: { item: "Firm Arrowhead", value: 0 },
			twoStar: { item: "Sharp Arrowhead", value: 0 },
			threeStar: { item: "Weathered Arrowhead", value: 0 },
		},
		region: { item: "Small Lamp Grass", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Dvalin's Sigh", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Firm Arrowhead", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sharp Arrowhead", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Weathered Arrowhead", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "ayaka",
	element: "cryo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Jade Sliver", value: 0 },
			threeStar: { item: "Jade Fragment", value: 0 },
			fourStar: { item: "Jade Chunk", value: 0 },
			fiveStar: { item: "Jade Gemstone", value: 0 },
		},
		boss: { item: "Perpetual Heart", value: 0 },
		common: {
			oneStar: { item: "Old Handguard", value: 0 },
			twoStar: { item: "Kageuchi Handguard", value: 0 },
			threeStar: { item: "Famed Handguard", value: 0 },
		},
		region: { item: "Sakura Bloom", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Bloodjade Branch", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Old Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Kageuchi Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Famed Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "ayato",
	element: "hydro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Lazurite Sliver", value: 0 },
			threeStar: { item: "Lazurite Fragment", value: 0 },
			fourStar: { item: "Lazurite Chunk", value: 0 },
			fiveStar: { item: "Lazurite Gemstone", value: 0 },
		},
		boss: { item: "Dew of Repudiation", value: 0 },
		common: {
			oneStar: { item: "Old Handguard", value: 0 },
			twoStar: { item: "Kageuchi Handguard", value: 0 },
			threeStar: { item: "Famed Handguard", value: 0 },
		},
		region: { item: "Sakura Bloom", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Mudra of the Malefic General", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Old Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Kageuchi Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Famed Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "barbara",
	element: "hydro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Lazurite Sliver", value: 0 },
			threeStar: { item: "Lazurite Fragment", value: 0 },
			fourStar: { item: "Lazurite Chunk", value: 0 },
			fiveStar: { item: "Lazurite Gemstone", value: 0 },
		},
		boss: { item: "Cleansing Heart", value: 0 },
		common: {
			oneStar: { item: "Divining Scroll", value: 0 },
			twoStar: { item: "Sealed Scroll", value: 0 },
			threeStar: { item: "Forbidden Scroll", value: 0 },
		},
		region: { item: "Philanemo Mushroom", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Ring of Boreas", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Divining Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sealed Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Forbidden Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "beidou",
	element: "electro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Amethyst Sliver", value: 0 },
			threeStar: { item: "Amethyst Fragment", value: 0 },
			fourStar: { item: "Amethyst Chunk", value: 0 },
			fiveStar: { item: "Amethyst Gemstone", value: 0 },
		},
		boss: { item: "Lightning Prism", value: 0 },
		common: {
			oneStar: { item: "Treasure Hoarder Insignia", value: 0 },
			twoStar: { item: "Silver Raven Insignia", value: 0 },
			threeStar: { item: "Golden Raven Insignia", value: 0 },
		},
		region: { item: "Noctilucous Jade", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Dvalin's Sigh", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Treasure Hoarder Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Silver Raven Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Golden Raven Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "bennett",
	element: "pyro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Agate Sliver", value: 0 },
			threeStar: { item: "Agate Fragment", value: 0 },
			fourStar: { item: "Agate Chunk", value: 0 },
			fiveStar: { item: "Agate Gemstone", value: 0 },
		},
		boss: { item: "Everflame Seed", value: 0 },
		common: {
			oneStar: { item: "Treasure Hoarder Insignia", value: 0 },
			twoStar: { item: "Silver Raven Insignia", value: 0 },
			threeStar: { item: "Golden Raven Insignia", value: 0 },
		},
		region: { item: "Windwheel Aster", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Dvalin's Plume", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Treasure Hoarder Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Silver Raven Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Golden Raven Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "chongyun",
	element: "cryo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Jade Sliver", value: 0 },
			threeStar: { item: "Jade Fragment", value: 0 },
			fourStar: { item: "Jade Chunk", value: 0 },
			fiveStar: { item: "Jade Gemstone", value: 0 },
		},
		boss: { item: "Hoarfrost Core", value: 0 },
		common: {
			oneStar: { item: "Damaged Mask", value: 0 },
			twoStar: { item: "Stained Mask", value: 0 },
			threeStar: { item: "Ominous Mask", value: 0 },
		},
		region: { item: "Cor Lapis", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Dvalin's Sigh", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Damaged Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Stained Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Ominous Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "diluc",
	element: "pyro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Agate Sliver", value: 0 },
			threeStar: { item: "Agate Fragment", value: 0 },
			fourStar: { item: "Agate Chunk", value: 0 },
			fiveStar: { item: "Agate Gemstone", value: 0 },
		},
		boss: { item: "Everflame Seed", value: 0 },
		common: {
			oneStar: { item: "Recruit's Insignia", value: 0 },
			twoStar: { item: "Sergeant's Insignia", value: 0 },
			threeStar: { item: "Lieutenant's Insignia", value: 0 },
		},
		region: { item: "Small Lamp Grass", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Dvalin's Plume", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Recruit's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sergeant's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Lieutenant's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
}, { 
	name: "diona",
	element: "cryo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Jade Sliver", value: 0 },
			threeStar: { item: "Jade Fragment", value: 0 },
			fourStar: { item: "Jade Chunk", value: 0 },
			fiveStar: { item: "Jade Gemstone", value: 0 },
		},
		boss: { item: "Hoarfrost Core", value: 0 },
		common: {
			oneStar: { item: "Firm Arrowhead", value: 0 },
			twoStar: { item: "Sharp Arrowhead", value: 0 },
			threeStar: { item: "Weathered Arrowhead", value: 0 },
		},
		region: { item: "Calla Lily", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Shard of a Foul Legacy", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Firm Arrowhead", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sharp Arrowhead", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Weathered Arrowhead", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
}, { 
	name: "eula",
	element: "cryo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Jade Sliver", value: 0 },
			threeStar: { item: "Jade Fragment", value: 0 },
			fourStar: { item: "Jade Chunk", value: 0 },
			fiveStar: { item: "Jade Gemstone", value: 0 },
		},
		boss: { item: "Crystalline Bloom", value: 0 },
		common: {
			oneStar: { item: "Damaged Mask", value: 0 },
			twoStar: { item: "Stained Mask", value: 0 },
			threeStar: { item: "Ominous Mask", value: 0 },
		},
		region: { item: "Dandelion Seed", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Dragon Lord's Crown", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Damaged Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Stained Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Ominous Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "fischl",
	element: "electro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Amethyst Sliver", value: 0 },
			threeStar: { item: "Amethyst Fragment", value: 0 },
			fourStar: { item: "Amethyst Chunk", value: 0 },
			fiveStar: { item: "Amethyst Gemstone", value: 0 },
		},
		boss: { item: "Lightning Prism", value: 0 },
		common: {
			oneStar: { item: "Firm Arrowhead", value: 0 },
			twoStar: { item: "Sharp Arrowhead", value: 0 },
			threeStar: { item: "Weathered Arrowhead", value: 0 },
		},
		region: { item: "Small Lamp Grass", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Spirit Locket of Boreas", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Firm Arrowhead", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sharp Arrowhead", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Weathered Arrowhead", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
}, { 
	name: "ganyu",
	element: "cryo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Jade Sliver", value: 0 },
			threeStar: { item: "Jade Fragment", value: 0 },
			fourStar: { item: "Jade Chunk", value: 0 },
			fiveStar: { item: "Jade Gemstone", value: 0 },
		},
		boss: { item: "Hoarfrost Core", value: 0 },
		common: {
			oneStar: { item: "Whopperflower Nectar", value: 0 },
			twoStar: { item: "Shimmering Nectar", value: 0 },
			threeStar: { item: "Energy Nectar", value: 0 },
		},
		region: { item: "Qingxin", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Shadow of the Warrior", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Whopperflower Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Shimmering Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Energy Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "gorou",
	element: "geo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Topaz Sliver", value: 0 },
			threeStar: { item: "Topaz Fragment", value: 0 },
			fourStar: { item: "Topaz Chunk", value: 0 },
			fiveStar: { item: "Topaz Gemstone", value: 0 },
		},
		boss: { item: "Perpetual Heart", value: 0 },
		common: {
			oneStar: { item: "Spectral Husk", value: 0 },
			twoStar: { item: "Spectral Heart", value: 0 },
			threeStar: { item: "Spectral Nucleus", value: 0 },
		},
		region: { item: "Sango Pearl", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Molten Moment", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Spectral Husk", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Spectral Heart", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Spectral Nucleus", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "hu tao",
	element: "pyro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Agate Sliver", value: 0 },
			threeStar: { item: "Agate Fragment", value: 0 },
			fourStar: { item: "Agate Chunk", value: 0 },
			fiveStar: { item: "Agate Gemstone", value: 0 },
		},
		boss: { item: "Juvenile Jade", value: 0 },
		common: {
			oneStar: { item: "Whopperflower Nectar", value: 0 },
			twoStar: { item: "Shimmering Nectar", value: 0 },
			threeStar: { item: "Energy Nectar", value: 0 },
		},
		region: { item: "Silk Flower", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Shard of a Foul Legacy", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Whopperflower Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Shimmering Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Energy Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "itto",
	element: "geo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Topaz Sliver", value: 0 },
			threeStar: { item: "Topaz Fragment", value: 0 },
			fourStar: { item: "Topaz Chunk", value: 0 },
			fiveStar: { item: "Topaz Gemstone", value: 0 },
		},
		boss: { item: "Riftborn Regalia", value: 0 },
		common: {
			oneStar: { item: "Slime Condensate", value: 0 },
			twoStar: { item: "Slime Secretions", value: 0 },
			threeStar: { item: "Slime Concentrate", value: 0 },
		},
		region: { item: "Onikabuto", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Ashen Heart", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Slime Condensate", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Slime Secretions", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Slime Concentrate", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "jean",
	element: "anemo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Turquoise Sliver", value: 0 },
			threeStar: { item: "Turquoise Fragment", value: 0 },
			fourStar: { item: "Turquoise Chunk", value: 0 },
			fiveStar: { item: "Turquoise Gemstone", value: 0 },
		},
		boss: { item: "Hurricane Seed", value: 0 },
		common: {
			oneStar: { item: "Damaged Mask", value: 0 },
			twoStar: { item: "Stained Mask", value: 0 },
			threeStar: { item: "Ominous Mask", value: 0 },
		},
		region: { item: "Dandelion Seed", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Dvalin's Plume", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Damaged Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Stained Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Ominous Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "kaeya",
	element: "cryo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Jade Sliver", value: 0 },
			threeStar: { item: "Jade Fragment", value: 0 },
			fourStar: { item: "Jade Chunk", value: 0 },
			fiveStar: { item: "Jade Gemstone", value: 0 },
		},
		boss: { item: "Hoarfrost Core", value: 0 },
		common: {
			oneStar: { item: "Treasure Hoarder Insignia", value: 0 },
			twoStar: { item: "Silver Raven Insignia", value: 0 },
			threeStar: { item: "Golden Raven Insignia", value: 0 },
		},
		region: { item: "Calla Lily", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Spirit Locket of Boreas", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Treasure Hoarder Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Silver Raven Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Golden Raven Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{  
	name: "kazuha",
	element: "anemo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Turquoise Sliver", value: 0 },
			threeStar: { item: "Turquoise Fragment", value: 0 },
			fourStar: { item: "Turquoise Chunk", value: 0 },
			fiveStar: { item: "Turquoise Gemstone", value: 0 },
		},
		boss: { item: "Marionette Core", value: 0 },
		common: {
			oneStar: { item: "Treasure Hoarder Insignia", value: 0 },
			twoStar: { item: "Silver Raven Insignia", value: 0 },
			threeStar: { item: "Golden Raven Insignia", value: 0 },
		},
		region: { item: "Sea Ganoderma", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Gilded Scale", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Treasure Hoarder Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Silver Raven Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Golden Raven Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "keqing",
	element: "electro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Amethyst Sliver", value: 0 },
			threeStar: { item: "Amethyst Fragment", value: 0 },
			fourStar: { item: "Amethyst Chunk", value: 0 },
			fiveStar: { item: "Amethyst Gemstone", value: 0 },
		},
		boss: { item: "Lightning Prism", value: 0 },
		common: {
			oneStar: { item: "Whopperflower Nectar", value: 0 },
			twoStar: { item: "Shimmering Nectar", value: 0 },
			threeStar: { item: "Energy Nectar", value: 0 },
		},
		region: { item: "Cor Lapis", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Ring of Boreas", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Whopperflower Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Shimmering Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Energy Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "klee",
	element: "pyro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Agate Sliver", value: 0 },
			threeStar: { item: "Agate Fragment", value: 0 },
			fourStar: { item: "Agate Chunk", value: 0 },
			fiveStar: { item: "Agate Gemstone", value: 0 },
		},
		boss: { item: "Everflame Seed", value: 0 },
		common: {
			oneStar: { item: "Divining Scroll", value: 0 },
			twoStar: { item: "Sealed Scroll", value: 0 },
			threeStar: { item: "Forbidden Scroll", value: 0 },
		},
		region: { item: "Philanemo Mushroom", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Ring of Boreas", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Divining Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sealed Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Forbidden Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "kokomi",
	element: "hydro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Lazurite Sliver", value: 0 },
			threeStar: { item: "Lazurite Fragment", value: 0 },
			fourStar: { item: "Lazurite Chunk", value: 0 },
			fiveStar: { item: "Lazurite Gemstone", value: 0 },
		},
		boss: { item: "Dew of Repudiation", value: 0 },
		common: {
			oneStar: { item: "Spectral Husk", value: 0 },
			twoStar: { item: "Spectral Heart", value: 0 },
			threeStar: { item: "Spectral Nucleus", value: 0 },
		},
		region: { item: "Sango Pearl", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Transience", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Transience", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Transience", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Hellfire Butterfly", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Spectral Husk", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Spectral Heart", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Spectral Nucleus", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "kuki shinobu",
	element: "electro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Amethyst Sliver", value: 0 },
			threeStar: { item: "Amethyst Fragment", value: 0 },
			fourStar: { item: "Amethyst Chunk", value: 0 },
			fiveStar: { item: "Amethyst Gemstone", value: 0 },
		},
		boss: { item: "Runic Fang", value: 0 },
		common: {
			oneStar: { item: "Spectral Husk", value: 0 },
			twoStar: { item: "Spectral Heart", value: 0 },
			threeStar: { item: "Spectral Nucleus", value: 0 },
		},
		region: { item: "Naku Weed", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Tears of the Calamitous God", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Spectral Husk", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Spectral Heart", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Spectral Nucleus", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "lisa",
	element: "electro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Amethyst Sliver", value: 0 },
			threeStar: { item: "Amethyst Fragment", value: 0 },
			fourStar: { item: "Amethyst Chunk", value: 0 },
			fiveStar: { item: "Amethyst Gemstone", value: 0 },
		},
		boss: { item: "Lightning Prism", value: 0 },
		common: {
			oneStar: { item: "Slime Condensate", value: 0 },
			twoStar: { item: "Slime Secretions", value: 0 },
			threeStar: { item: "Slime Concentrate", value: 0 },
		},
		region: { item: "Valberry", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Dvalin's Claw", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Slime Condensate", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Slime Secretions", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Slime Concentrate", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "mona",
	element: "hydro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Lazurite Sliver", value: 0 },
			threeStar: { item: "Lazurite Fragment", value: 0 },
			fourStar: { item: "Lazurite Chunk", value: 0 },
			fiveStar: { item: "Lazurite Gemstone", value: 0 },
		},
		boss: { item: "Cleasning Heart", value: 0 },
		common: {
			oneStar: { item: "Whopperflower Nectar", value: 0 },
			twoStar: { item: "Shimmering Nectar", value: 0 },
			threeStar: { item: "Energy Nectar", value: 0 },
		},
		region: { item: "Philanemo Mushroom", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Ring of Boreas", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Whopperflower Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Shimmering Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Energy Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "ningguang",
	element: "geo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Topaz Sliver", value: 0 },
			threeStar: { item: "Topaz Fragment", value: 0 },
			fourStar: { item: "Topaz Chunk", value: 0 },
			fiveStar: { item: "Topaz Gemstone", value: 0 },
		},
		boss: { item: "Basalt Pillar", value: 0 },
		common: {
			oneStar: { item: "Recruit's Insignia", value: 0 },
			twoStar: { item: "Sergeant's Insignia", value: 0 },
			threeStar: { item: "Lieutenant's Insignia", value: 0 },
		},
		region: { item: "Glaze Lily", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Spirit Locket of Boreas", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Recruit's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sergeant's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Lieutenant's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "noelle",
	element: "geo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Topaz Sliver", value: 0 },
			threeStar: { item: "Topaz Fragment", value: 0 },
			fourStar: { item: "Topaz Chunk", value: 0 },
			fiveStar: { item: "Topaz Gemstone", value: 0 },
		},
		boss: { item: "Basalt Pillar", value: 0 },
		common: {
			oneStar: { item: "Damaged Mask", value: 0 },
			twoStar: { item: "Stained Mask", value: 0 },
			threeStar: { item: "Ominous Mask", value: 0 },
		},
		region: { item: "Valberry", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Dvalin's Claw", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Damaged Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Stained Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Ominous Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "qiqi",
	element: "cryo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Jade Sliver", value: 0 },
			threeStar: { item: "Jade Fragment", value: 0 },
			fourStar: { item: "Jade Chunk", value: 0 },
			fiveStar: { item: "Jade Gemstone", value: 0 },
		},
		boss: { item: "Hoarfrost Core", value: 0 },
		common: {
			oneStar: { item: "Divining Scroll", value: 0 },
			twoStar: { item: "Sealed Scroll", value: 0 },
			threeStar: { item: "Forbidden Scroll", value: 0 },
		},
		region: { item: "Violetgrass", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Tail of Boreas", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Divining Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sealed Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Forbidden Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "raiden",
	element: "electro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Amethyst Sliver", value: 0 },
			threeStar: { item: "Amethyst Fragment", value: 0 },
			fourStar: { item: "Amethyst Chunk", value: 0 },
			fiveStar: { item: "Amethyst Gemstone", value: 0 },
		},
		boss: { item: "Storm Beads", value: 0 },
		common: {
			oneStar: { item: "Old Handguard", value: 0 },
			twoStar: { item: "Kageuchi Handguard", value: 0 },
			threeStar: { item: "Famed Handguard", value: 0 },
		},
		region: { item: "Amakumo Fruit", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Molten Moment", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Old Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Kageuchi Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Famed Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "razor",
	element: "electro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Amethyst Sliver", value: 0 },
			threeStar: { item: "Amethyst Fragment", value: 0 },
			fourStar: { item: "Amethyst Chunk", value: 0 },
			fiveStar: { item: "Amethyst Gemstone", value: 0 },
		},
		boss: { item: "Lightning Prism", value: 0 },
		common: {
			oneStar: { item: "Damaged Mask", value: 0 },
			twoStar: { item: "Stained Mask", value: 0 },
			threeStar: { item: "Ominous Mask", value: 0 },
		},
		region: { item: "Wolfhook", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Dvalin's Claw", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Damaged Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Stained Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Ominous Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "rosaria",
	element: "cryo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Jade Sliver", value: 0 },
			threeStar: { item: "Jade Fragment", value: 0 },
			fourStar: { item: "Jade Chunk", value: 0 },
			fiveStar: { item: "Jade Gemstone", value: 0 },
		},
		boss: { item: "Hoarfrost Core", value: 0 },
		common: {
			oneStar: { item: "Recruit's Insignia", value: 0 },
			twoStar: { item: "Sergeant's Insignia", value: 0 },
			threeStar: { item: "Lieutenant's Insignia", value: 0 },
		},
		region: { item: "Valberry", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Shadow of the Warrior", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Recruit's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sergeant's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Lieutenant's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "sara",
	element: "electro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Amethyst Sliver", value: 0 },
			threeStar: { item: "Amethyst Fragment", value: 0 },
			fourStar: { item: "Amethyst Chunk", value: 0 },
			fiveStar: { item: "Amethyst Gemstone", value: 0 },
		},
		boss: { item: "Storm Beads", value: 0 },
		common: {
			oneStar: { item: "Damaged Mask", value: 0 },
			twoStar: { item: "Stained Mask", value: 0 },
			threeStar: { item: "Ominous Mask", value: 0 },
		},
		region: { item: "Dendrobrium", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Ashen Heart", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Damaged Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Stained Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Ominous Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "sayu",
	element: "anemo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Turquoise Sliver", value: 0 },
			threeStar: { item: "Turquoise Fragment", value: 0 },
			fourStar: { item: "Turquoise Chunk", value: 0 },
			fiveStar: { item: "Turquoise Gemstone", value: 0 },
		},
		boss: { item: "Marionette Core", value: 0 },
		common: {
			oneStar: { item: "Whopperflower Nectar", value: 0 },
			twoStar: { item: "Shimmering Nectar", value: 0 },
			threeStar: { item: "Energy Nectar", value: 0 },
		},
		region: { item: "Crystal Marrow", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Gilded Scale", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Whopperflower Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Shimmering Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Energy Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "shenhe",
	element: "cryo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Jade Sliver", value: 0 },
			threeStar: { item: "Jade Fragment", value: 0 },
			fourStar: { item: "Jade Chunk", value: 0 },
			fiveStar: { item: "Jade Gemstone", value: 0 },
		},
		boss: { item: "Dragonheir's False Fin", value: 0 },
		common: {
			oneStar: { item: "Whopperflower Nectar", value: 0 },
			twoStar: { item: "Shimmering Nectar", value: 0 },
			threeStar: { item: "Energy Nectar", value: 0 },
		},
		region: { item: "Qingxin", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Hellfire Butterfly", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Whopperflower Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Shimmering Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Energy Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "sucrose",
	element: "anemo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Turquoise Sliver", value: 0 },
			threeStar: { item: "Turquoise Fragment", value: 0 },
			fourStar: { item: "Turquoise Chunk", value: 0 },
			fiveStar: { item: "Turquoise Gemstone", value: 0 },
		},
		boss: { item: "Hurricane Seed", value: 0 },
		common: {
			oneStar: { item: "Whopperflower Nectar", value: 0 },
			twoStar: { item: "Shimmering Nectar", value: 0 },
			threeStar: { item: "Energy Nectar", value: 0 },
		},
		region: { item: "Windwheel Aster", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Spirit Locket of Boreas", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Whopperflower Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Shimmering Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Energy Nectar", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "tartaglia",
	element: "hydro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Lazurite Sliver", value: 0 },
			threeStar: { item: "Lazurite Fragment", value: 0 },
			fourStar: { item: "Lazurite Chunk", value: 0 },
			fiveStar: { item: "Lazurite Gemstone", value: 0 },
		},
		boss: { item: "Cleansing Heart", value: 0 },
		common: {
			oneStar: { item: "Recruit's Insignia", value: 0 },
			twoStar: { item: "Sergeant's Insignia", value: 0 },
			threeStar: { item: "Lieutenant's Insignia", value: 0 },
		},
		region: { item: "Starconch", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Shard of a Foul Legacy", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Recruit's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sergeant's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Lieutenant's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "thoma",
	element: "pyro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Agate Sliver", value: 0 },
			threeStar: { item: "Agate Fragment", value: 0 },
			fourStar: { item: "Agate Chunk", value: 0 },
			fiveStar: { item: "Agate Gemstone", value: 0 },
		},
		boss: { item: "Smoldering Pearl", value: 0 },
		common: {
			oneStar: { item: "Recruit's Insignia", value: 0 },
			twoStar: { item: "Sergeant's Insignia", value: 0 },
			threeStar: { item: "Lieutenant's Insignia", value: 0 },
		},
		region: { item: "Fluorescent Fungus", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Transience", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Transience", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Transience", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Hellfire Butterfly", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Recruit's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sergeant's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Lieutenant's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "venti",
	element: "anemo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Turquoise Sliver", value: 0 },
			threeStar: { item: "Turquoise Fragment", value: 0 },
			fourStar: { item: "Turquoise Chunk", value: 0 },
			fiveStar: { item: "Turquoise Gemstone", value: 0 },
		},
		boss: { item: "Hurricane Seed", value: 0 },
		common: {
			oneStar: { item: "Slime Condensate", value: 0 },
			twoStar: { item: "Slime Secretions", value: 0 },
			threeStar: { item: "Slime Concentrate", value: 0 },
		},
		region: { item: "Cecilia", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Tail of Boreas", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Slime Condensate", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Slime Secretions", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Slime Concentrate", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "xiangling",
	element: "pyro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Agate Sliver", value: 0 },
			threeStar: { item: "Agate Fragment", value: 0 },
			fourStar: { item: "Agate Chunk", value: 0 },
			fiveStar: { item: "Agate Gemstone", value: 0 },
		},
		boss: { item: "Everflame Seed", value: 0 },
		common: {
			oneStar: { item: "Slime Condensate", value: 0 },
			twoStar: { item: "Slime Secretions", value: 0 },
			threeStar: { item: "Slime Concentrate", value: 0 },
		},
		region: { item: "Jueyun Chili", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Dvalin's Claw", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Slime Condensate", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Slime Secretions", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Slime Concentrate", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "xiao",
	element: "anemo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Turquoise Sliver", value: 0 },
			threeStar: { item: "Turquoise Fragment", value: 0 },
			fourStar: { item: "Turquoise Chunk", value: 0 },
			fiveStar: { item: "Turquoise Gemstone", value: 0 },
		},
		boss: { item: "Juvenile Jade", value: 0 },
		common: {
			oneStar: { item: "Slime Condensate", value: 0 },
			twoStar: { item: "Slime Secretions", value: 0 },
			threeStar: { item: "Slime Concentrate", value: 0 },
		},
		region: { item: "Qingxin", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Shadow of the Warrior", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Slime Condensate", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Slime Secretions", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Slime Concentrate", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "xingqiu",
	element: "hydro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Lazurite Sliver", value: 0 },
			threeStar: { item: "Lazurite Fragment", value: 0 },
			fourStar: { item: "Lazurite Chunk", value: 0 },
			fiveStar: { item: "Lazurite Gemstone", value: 0 },
		},
		boss: { item: "Cleansing Heart", value: 0 },
		common: {
			oneStar: { item: "Damaged Mask", value: 0 },
			twoStar: { item: "Stained Mask", value: 0 },
			threeStar: { item: "Ominous Mask", value: 0 },
		},
		region: { item: "Silk Flower", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Tail of Boreas", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Damaged Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Stained Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Ominous Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "xinyan",
	element: "pyro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Agate Sliver", value: 0 },
			threeStar: { item: "Agate Fragment", value: 0 },
			fourStar: { item: "Agate Chunk", value: 0 },
			fiveStar: { item: "Agate Gemstone", value: 0 },
		},
		boss: { item: "Everflame Seed", value: 0 },
		common: {
			oneStar: { item: "Treasure Hoarder Insignia", value: 0 },
			twoStar: { item: "Silver Raven Insignia", value: 0 },
			threeStar: { item: "Golden Raven Insignia", value: 0 },
		},
		region: { item: "Violetgrass", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Tusk of Monoceros Caeli", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Treasure Hoarder Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Silver Raven Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Golden Raven Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "yae miko",
	element: "electro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Amethyst Sliver", value: 0 },
			threeStar: { item: "Amethyst Fragment", value: 0 },
			fourStar: { item: "Amethyst Chunk", value: 0 },
			fiveStar: { item: "Amethyst Gemstone", value: 0 },
		},
		boss: { item: "Dragonheir's False Fin", value: 0 },
		common: {
			oneStar: { item: "Old Handguard", value: 0 },
			twoStar: { item: "Kageuchi Handguard", value: 0 },
			threeStar: { item: "Famed Handguard", value: 0 },
		},
		region: { item: "Sea Ganoderma", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "The Meaning of Aeons", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Old Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Kageuchi Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Famed Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "yanfei",
	element: "pyro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Agate Sliver", value: 0 },
			threeStar: { item: "Agate Fragment", value: 0 },
			fourStar: { item: "Agate Chunk", value: 0 },
			fiveStar: { item: "Agate Gemstone", value: 0 },
		},
		boss: { item: "Juvenile Jade", value: 0 },
		common: {
			oneStar: { item: "Treasure Hoarder Insignia", value: 0 },
			twoStar: { item: "Silver Raven Insignia", value: 0 },
			threeStar: { item: "Golden Raven Insignia", value: 0 },
		},
		region: { item: "Noctilucous Jade", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Bloodjade Branch", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Treasure Hoarder Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Silver Raven Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Golden Raven Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "yelan",
	element: "hydro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Lazurite Sliver", value: 0 },
			threeStar: { item: "Lazurite Fragment", value: 0 },
			fourStar: { item: "Lazurite Chunk", value: 0 },
			fiveStar: { item: "Lazurite Gemstone", value: 0 },
		},
		boss: { item: "Runic Fang", value: 0 },
		common: {
			oneStar: { item: "Recruit's Insignia", value: 0 },
			twoStar: { item: "Sergeant's Insignia", value: 0 },
			threeStar: { item: "Lieutenant's Insignia", value: 0 },
		},
		region: { item: "Starconch", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Prosperity", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Gilded Scale", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Recruit's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sergeant's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Lieutenant's Insignia", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "yoimiya",
	element: "pyro",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Agate Sliver", value: 0 },
			threeStar: { item: "Agate Fragment", value: 0 },
			fourStar: { item: "Agate Chunk", value: 0 },
			fiveStar: { item: "Agate Gemstone", value: 0 },
		},
		boss: { item: "Smoldering Pearl", value: 0 },
		common: {
			oneStar: { item: "Divining Scroll", value: 0 },
			twoStar: { item: "Sealed Scroll", value: 0 },
			threeStar: { item: "Forbidden Scroll", value: 0 },
		},
		region: { item: "Naku Weed", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Transience", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Transience", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Transience", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Dragon Lord's Crown", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: { 
			oneStar: { item: "Divining Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Sealed Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Forbidden Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "yun jin",
	element: "geo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Topaz Sliver", value: 0 },
			threeStar: { item: "Topaz Fragment", value: 0 },
			fourStar: { item: "Topaz Chunk", value: 0 },
			fiveStar: { item: "Topaz Gemstone", value: 0 },
		},
		boss: { item: "Riftborn Regalia", value: 0 },
		common: {
			oneStar: { item: "Damaged Mask", value: 0 },
			twoStar: { item: "Stained Mask", value: 0 },
			threeStar: { item: "Ominous Mask", value: 0 },
		},
		region: { item: "Glaze Lily", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Diligence", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Ashen Heart", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Damaged Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Stained Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Ominous Mask", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},{ 
	name: "zhongli",
	element: "geo",
	ascension: 0,
	owned: false,
	fav: false,
	talent1: 1,
	talent2: 1,
	talent3: 1,
	properties: {
		ascension: { 
			twoStar: { item: "Topaz Sliver", value: 0 },
			threeStar: { item: "Topaz Fragment", value: 0 },
			fourStar: { item: "Topaz Chunk", value: 0 },
			fiveStar: { item: "Topaz Gemstone", value: 0 },
		},
		boss: { item: "Basalt Pillar", value: 0 },
		common: {
			oneStar: { item: "Slime Condensate", value: 0 },
			twoStar: { item: "Slime Secretions", value: 0 },
			threeStar: { item: "Slime Concentrate", value: 0 },
		},
		region: { item: "Cor Lapis", value: 0 },
		crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talent: {
			twoStar: { item: "Teachings of Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Guide to Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
			fourStar: { item: "Philosophies of Gold", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
		talBoss: { item: "Tusk of the Monoceros Caeli", value: { tal1: 0, tal2: 0, tal3: 0 }},
		talCommon: {
			oneStar: { item: "Slime Condensate", value: { tal1: 0, tal2: 0, tal3: 0 }},
			twoStar: { item: "Slime Secretions", value: { tal1: 0, tal2: 0, tal3: 0 }},
			threeStar: { item: "Slime Concentrate", value: { tal1: 0, tal2: 0, tal3: 0 }},
		},
	}
},]