export const gemChars = [
    { item: "Agate Sliver", chars: ["Amber", "Bennett", "Diluc", "Klee", "Hu Tao", "Thoma", "Xiangling", "Xinyan", "Yanfei", "Yoimiya"]},
    { item: "Agate Fragment", chars: ["Amber", "Bennett", "Diluc", "Klee", "Hu Tao", "Thoma", "Xiangling", "Xinyan", "Yanfei", "Yoimiya"]},
    { item: "Agate Chunk", chars: ["Amber", "Bennett", "Diluc", "Klee", "Hu Tao", "Thoma", "Xiangling", "Xinyan", "Yanfei", "Yoimiya"]},
    { item: "Agate Gemstone", chars: ["Amber", "Bennett", "Diluc", "Klee", "Hu Tao", "Thoma", "Xiangling", "Xinyan", "Yanfei", "Yoimiya"]},
    { item: "Lazurite Sliver", chars: ["Ayato", "Barbara", "Candace", "Kokomi", "Mona", "Nilou", "Tartaglia", "Xingqiu", "Yelan"]},
    { item: "Lazurite Fragment", chars: ["Ayato", "Barbara", "Candace", "Kokomi", "Mona", "Nilou", "Tartaglia", "Xingqiu", "Yelan"]},
    { item: "Lazurite Chunk", chars: ["Ayato", "Barbara", "Candace", "Kokomi", "Mona", "Nilou", "Tartaglia", "Xingqiu", "Yelan"]},
    { item: "Lazurite Gemstone", chars: ["Ayato", "Barbara", "Candace", "Kokomi", "Mona", "Nilou", "Tartaglia", "Xingqiu", "Yelan"]},
    { item: "Emerald Sliver", chars: ["Alhaitham", "Collei", "Nahida", "Tighnari", "Yaoyao"]},
    { item: "Emerald Fragment", chars: ["Alhaitham", "Collei", "Nahida", "Tighnari", "Yaoyao"]},
    { item: "Emerald Chunk", chars: ["Alhaitham", "Collei", "Nahida", "Tighnari", "Yaoyao"]},
    { item: "Emerald Gemstone", chars: ["Alhaitham", "Collei", "Nahida", "Tighnari", "Yaoyao"]},
    { item: "Amethyst Sliver", chars: ["Beidou", "Cyno", "Dori", "Fischl", "Keqing", "Lisa", "Raiden", "Razor", "Sara", "Shinobu", "Yae Miko"]},
    { item: "Amethyst Fragment", chars: ["Beidou", "Cyno", "Dori", "Fischl", "Keqing", "Lisa", "Raiden", "Razor", "Sara", "Shinobu", "Yae Miko"]},
    { item: "Amethyst Chunk", chars: ["Beidou", "Cyno", "Dori", "Fischl", "Keqing", "Lisa", "Raiden", "Razor", "Sara", "Shinobu", "Yae Miko"]},
    { item: "Amethyst Gemstone", chars: ["Beidou", "Cyno", "Dori", "Fischl", "Keqing", "Lisa", "Raiden", "Razor", "Sara", "Shinobu", "Yae Miko"]},
    { item: "Turquoise Sliver", chars: ["Faruzan", "Heizou", "Jean", "Kazuha", "Sayu", "Sucrose", "Venti", "Wanderer", "Xiao"]},
    { item: "Turquoise Fragment", chars: ["Faruzan", "Heizou", "Jean", "Kazuha", "Sayu", "Sucrose", "Venti", "Wanderer", "Xiao"]},
    { item: "Turquoise Chunk", chars: ["Faruzan", "Heizou", "Jean", "Kazuha", "Sayu", "Sucrose", "Venti", "Wanderer", "Xiao"]},
    { item: "Turquoise Gemstone", chars: ["Faruzan", "Heizou", "Jean", "Kazuha", "Sayu", "Sucrose", "Venti", "Wanderer", "Xiao"]},
    { item: "Jade Sliver", chars: ["Aloy", "Ayaka", "Chongyun", "Diona", "Eula", "Ganyu", "Kaeya", "Layla", "Qiqi", "Rosaria", "Shenhe"]},
    { item: "Jade Fragment", chars: ["Aloy", "Ayaka", "Chongyun", "Diona", "Eula", "Ganyu", "Kaeya", "Layla", "Qiqi", "Rosaria", "Shenhe"]},
    { item: "Jade Chunk", chars: ["Aloy", "Ayaka", "Chongyun", "Diona", "Eula", "Ganyu", "Kaeya", "Layla", "Qiqi", "Rosaria", "Shenhe"]},
    { item: "Jade Gemstone", chars: ["Aloy", "Ayaka", "Chongyun", "Diona", "Eula", "Ganyu", "Kaeya", "Layla", "Qiqi", "Rosaria", "Shenhe"]},
    { item: "Topaz Sliver", chars: ["Albedo", "Gorou", "Itto", "Ningguang", "Noelle", "Yun Jin", "Zhongli"]},
    { item: "Topaz Fragment", chars: ["Albedo", "Gorou", "Itto", "Ningguang", "Noelle", "Yun Jin", "Zhongli"]},
    { item: "Topaz Chunk", chars: ["Albedo", "Gorou", "Itto", "Ningguang", "Noelle", "Yun Jin", "Zhongli"]},
    { item: "Topaz Gemstone", chars: ["Albedo", "Gorou", "Itto", "Ningguang", "Noelle", "Yun Jin", "Zhongli"]},
    { item: "Brilliant Diamond Sliver", chars: ["Aether", "Lumine"]},
    { item: "Brilliant Diamond Fragment", chars: ["Aether", "Lumine"]},
    { item: "Brilliant Diamond Chunk", chars: ["Aether", "Lumine"]},
    { item: "Brilliant Diamond Gemstone", chars: ["Aether", "Lumine"]}
]

export const localSpecialties = [
    { item: "Calla Lily", chars: ["Diona", "Kaeya"]},
    { item: "Wolfhook", chars: ["Razor"]},
    { item: "Valberry", chars: ["Lisa", "Noelle", "Rosaria"]},
    { item: "Cecilia", chars: ["Albedo", "Venti"]},
    { item: "Windwheel Aster", chars: ["Aether", "Lumine", "Bennett", "Sucrose"]},
    { item: "Philanemo Mushroom", chars: ["Barbara", "Klee", "Mona"]},
    { item: "Jueyun Chili", chars: ["Xiangling", "Yaoyao"]},
    { item: "Noctilucous Jade", chars: ["Beidou", "Yanfei"]},
    { item: "Silk Flower", chars: ["Hu Tao", "Xingqiu"]},
    { item: "Glaze Lily", chars: ["Ningguang", "Yun Jin"]},
    { item: "Qingxin", chars: ["Ganyu", "Shenhe", "Xiao"]},
    { item: "Starconch", chars: ["Tartaglia", "Yelan"]},
    { item: "Violetgrass", chars: ["Qiqi", "Xinyan"]},
    { item: "Small Lamp Grass", chars: ["Amber", "Diluc", "Fischl"]},
    { item: "Dandelion Seed", chars: ["Eula", "Jean"]},
    { item: "Cor Lapis", chars: ["Chongyun", "Keqing", "Zhongli"]},
    { item: "Onikabuto", chars: ["Heizou", "Itto"]},
    { item: "Sakura Bloom", chars: ["Ayaka", "Ayato"]},
    { item: "Crystal Marrow", chars: ["Aloy", "Sayu"]},
    { item: "Dendrobrium", chars: ["Sara"]},
    { item: "Naku Weed", chars: ["Shinobu", "Yoimiya"]},
    { item: "Sea Ganoderma", chars: ["Kazuha", "Yae Miko"]},
    { item: "Sango Pearl", chars: ["Gorou", "Kokomi"]},
    { item: "Amakumo Fruit", chars: ["Raiden"]},
    { item: "Fluorescent Fungus", chars: ["Thoma"]},
    { item: "Rukkhashava Mushrooms", chars: ["Collei", "Wanderer"]},
    { item: "Padisarah", chars: ["Nilou"]},
    { item: "Nilotpala Lotus", chars: ["Layla", "Tighnari"]},
    { item: "Kalpalata Lotus", chars: ["Dori", "Nahida"]},
    { item: "Redcrest", chars: ["Candace", "Faruzan"]},
    { item: "Sand Grease Pupa", chars: ["Alhaitham"]},
    { item: "Scarab", chars: ["Cyno"]},
]

export const commons = [
    { item: "Slime Condensate", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Yaoyao", "Zhongli"] },
    { item: "Slime Secretions", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Yaoyao", "Zhongli"] },
    { item: "Slime Concentrate", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Yaoyao", "Zhongli"] },
    { item: "Damaged Mask", chars: ["Aether", "Chongyun", "Eula", "Jean", "Lumine", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Stained Mask", chars: ["Aether", "Chongyun", "Eula", "Jean", "Lumine", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Ominous Mask", chars: ["Aether", "Chongyun", "Eula", "Jean", "Lumine", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Divining Scroll", chars: ["Albedo", "Barbara", "Cyno", "Klee", "Layla", "Qiqi", "Yoimiya"] },
    { item: "Sealed Scroll", chars: ["Albedo", "Barbara", "Cyno", "Klee", "Layla", "Qiqi", "Yoimiya"] },
    { item: "Forbidden Scroll", chars: ["Albedo", "Barbara", "Cyno", "Klee", "Layla", "Qiqi", "Yoimiya"] },
    { item: "Firm Arrowhead", chars: ["Amber", "Collei", "Diona", "Fischl"] },
    { item: "Sharp Arrowhead", chars: ["Amber", "Collei", "Diona", "Fischl"] },
    { item: "Weathered Arrowhead", chars: ["Amber", "Collei", "Diona", "Fischl"] },
    { item: "Recruit's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia", "Yelan"] },
    { item: "Sergeant's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia", "Yelan"] },
    { item: "Lieutenant's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia", "Yelan"] },
    { item: "Treasure Hoarder Insignia", chars: ["Beidou", "Bennett", "Heizou", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Silver Raven Insignia", chars: ["Beidou", "Bennett", "Heizou", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Golden Raven Insignia", chars: ["Beidou", "Bennett", "Heizou", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Whopperflower Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Shimmering Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Energy Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Old Handguard", chars: ["Ayaka", "Ayato", "Raiden", "Wanderer", "Yae Miko"] },
    { item: "Kageuchi Handguard", chars: ["Ayaka", "Ayato", "Raiden", "Wanderer", "Yae Miko"] },
    { item: "Famed Handguard", chars: ["Ayaka", "Ayato", "Raiden", "Wanderer", "Yae Miko"] },
    { item: "Spectral Husk", chars: ["Aloy", "Gorou", "Kokomi", "Shinobu"] },
    { item: "Spectral Heart", chars: ["Aloy", "Gorou", "Kokomi", "Shinobu"] },
    { item: "Spectral Nucleus", chars: ["Aloy", "Gorou", "Kokomi", "Shinobu"] },
    { item: "Fungal Spores", chars: ["Nahida", "Nilou", "Tighnari"] },
    { item: "Luminescent Pollen", chars: ["Nahida", "Nilou", "Tighnari"] },
    { item: "Crystalline Cyst Dust", chars: ["Nahida", "Nilou", "Tighnari"] },
    { item: "Faded Red Satin", chars: ["Alhaitham", "Candace", "Dori", "Faruzan"] },
    { item: "Trimmed Red Silk", chars: ["Alhaitham", "Candace", "Dori", "Faruzan"] },
    { item: "Rich Red Brocade", chars: ["Alhaitham", "Candace", "Dori", "Faruzan"] },
]

export const bossMats = [
    { item: "Hurricane Seed", chars: ["Jean", "Sucrose", "Venti"] },
    { item: "Lightning Prism", chars: ["Beidou", "Fischl", "Keqing", "Lisa", "Razor"] },
    { item: "Basalt Pillar", chars: ["Albedo", "Ningguang", "Noelle", "Zhongli"] },
    { item: "Hoarfrost Core", chars: ["Chongyun", "Diona", "Ganyu", "Kaeya", "Qiqi", "Rosaria"] },
    { item: "Everflame Seed", chars: ["Amber", "Bennett", "Diluc", "Klee", "Xiangling", "Xinyan"] },
    { item: "Cleansing Heart", chars: ["Barbara", "Mona", "Tartaglia", "Xingqiu"] },
    { item: "Juvenile Jade", chars: ["Hu Tao", "Xiao", "Yanfei"] },
    { item: "Crystalline Bloom", chars: ["Aloy", "Eula"] },
    { item: "Marionette Core", chars: ["Kazuha", "Sayu"] },
    { item: "Perpetual Heart", chars: ["Ayaka", "Gorou"] },
    { item: "Smoldering Pearl", chars: ["Thoma", "Yoimiya"] },
    { item: "Dew of Repudiation", chars: ["Ayato", "Kokomi"] },
    { item: "Storm Beads", chars: ["Raiden", "Sara"] },
    { item: "Riftborn Regalia", chars: ["Itto", "Yun Jin"] },
    { item: "Dragonheir's False Fin", chars: ["Shenhe", "Yae Miko"] },
    { item: "Runic Fang", chars: ["Heizou", "Shinobu", "Yelan"] },
    { item: "Majestic Hooked Beak", chars: ["Collei", "Tighnari"] },
    { item: "Thunderclap Fruitcore", chars: ["Cyno", "Dori"] },
    { item: "Perpetual Caliber", chars: ["Layla", "Nilou", "Wanderer"] },
    { item: "Light Guiding Tetrahedron", chars: ["Candace", "Faruzan"] },
    { item: "Quelled Creeper", chars: ["Nahida", "Yaoyao"] },
    { item: "Pseudo Stamens", chars: ["Alhaitham"] },
]

export const talCommon = [
    { item: "Slime Condensate", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Yaoyao", "Zhongli"] },
    { item: "Slime Secretions", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Yaoyao", "Zhongli"] },
    { item: "Slime Concentrate", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Yaoyao", "Zhongli"] },
    { item: "Damaged Mask", chars: ["Aether", "Chongyun", "Eula", "Jean", "Lumine", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Stained Mask", chars: ["Aether", "Chongyun", "Eula", "Jean", "Lumine", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Ominous Mask", chars: ["Aether", "Chongyun", "Eula", "Jean", "Lumine", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Divining Scroll", chars: ["Albedo", "Barbara", "Cyno", "Klee", "Layla", "Qiqi", "Yoimiya"] },
    { item: "Sealed Scroll", chars: ["Albedo", "Barbara", "Cyno", "Klee", "Layla", "Qiqi", "Yoimiya"] },
    { item: "Forbidden Scroll", chars: ["Albedo", "Barbara", "Cyno", "Klee", "Layla", "Qiqi", "Yoimiya"] },
    { item: "Firm Arrowhead", chars: ["Amber", "Collei", "Diona", "Fischl"] },
    { item: "Sharp Arrowhead", chars: ["Amber", "Collei", "Diona", "Fischl"] },
    { item: "Weathered Arrowhead", chars: ["Amber", "Collei", "Diona", "Fischl"] },
    { item: "Recruit's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia", "Yelan"] },
    { item: "Sergeant's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia", "Yelan"] },
    { item: "Lieutenant's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia", "Yelan"] },
    { item: "Treasure Hoarder Insignia", chars: ["Beidou", "Bennett", "Heizou", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Silver Raven Insignia", chars: ["Beidou", "Bennett", "Heizou", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Golden Raven Insignia", chars: ["Beidou", "Bennett", "Heizou", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Whopperflower Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Shimmering Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Energy Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Old Handguard", chars: ["Ayaka", "Ayato", "Raiden", "Wanderer", "Yae Miko"] },
    { item: "Kageuchi Handguard", chars: ["Ayaka", "Ayato", "Raiden", "Wanderer", "Yae Miko"] },
    { item: "Famed Handguard", chars: ["Ayaka", "Ayato", "Raiden", "Wanderer", "Yae Miko"] },
    { item: "Spectral Husk", chars: ["Aloy", "Gorou", "Kokomi", "Shinobu"] },
    { item: "Spectral Heart", chars: ["Aloy", "Gorou", "Kokomi", "Shinobu"] },
    { item: "Spectral Nucleus", chars: ["Aloy", "Gorou", "Kokomi", "Shinobu"] },
    { item: "Fungal Spores", chars: ["Nahida", "Nilou", "Tighnari"] },
    { item: "Luminescent Pollen", chars: ["Nahida", "Nilou", "Tighnari"] },
    { item: "Crystalline Cyst Dust", chars: ["Nahida", "Nilou", "Tighnari"] },
    { item: "Faded Red Satin", chars: ["Alhaitham", "Candace", "Dori", "Faruzan"] },
    { item: "Trimmed Red Silk", chars: ["Alhaitham", "Candace", "Dori", "Faruzan"] },
    { item: "Rich Red Brocade", chars: ["Alhaitham", "Candace", "Dori", "Faruzan"] },
]

export const crowns = [
    { item: "Crown of Sagehood", chars: ["Aether", "Lumine", "Albedo", "Alhaitham", "Aloy", "Amber", "Ayaka", "Ayato", "Barbara", "Beidou", "Bennett", "Candace", "Chongyun", "Collei", "Cyno", "Diluc", "Diona", "Dori", "Eula", "Faruzan", "Fischl", "Ganyu", "Gorou", "Heizou", "Hu Tao", "Itto", "Jean", "Kaeya", "Kazuha", "Keqing", "Klee", "Kokomi", "Shinobu", "Layla", "Lisa", "Mona", "Nahida", "Nilou", "Ningguang", "Noelle", "Qiqi", "Raiden", "Razor", "Rosaria", "Sara", "Sayu", "Shenhe", "Sucrose", "Tartaglia", "Thoma", "Tighnari", "Venti", "Wanderer", "Xiao", "Xiangling", "Xingqiu", "Xinyan", "Yae Miko", "Yaoyao", "Yanfei", "Yelan", "Yoimiya", "Yun Jin", "Zhongli"]}
]

export const books = [
    { item: "Teachings of Freedom", chars: ["Aether", "Lumine", "Aloy", "Amber", "Barbara", "Diona", "Klee", "Sucrose", "Tartaglia"]},
    { item: "Guide to Freedom", chars: ["Aether", "Lumine", "Aloy", "Amber", "Barbara", "Diona", "Klee", "Sucrose", "Tartaglia"]},
    { item: "Philosophies of Freedom", chars: ["Aether", "Lumine", "Aloy", "Amber", "Barbara", "Diona", "Klee", "Sucrose", "Tartaglia"]},
    { item: "Teachings of Resistance", chars: ["Bennett", "Diluc", "Eula", "Jean", "Mona", "Noelle", "Razor"]},
    { item: "Guide to Resistance", chars: ["Aether", "Lumine", "Bennett", "Diluc", "Eula", "Jean", "Mona", "Noelle", "Razor"]},
    { item: "Philosophies of Resistance", chars: ["Aether", "Lumine", "Bennett", "Diluc", "Eula", "Jean", "Mona", "Noelle", "Razor"]},
    { item: "Teachings of Ballad", chars: ["Albedo", "Fischl", "Kaeya", "Lisa", "Rosaria", "Venti"]},
    { item: "Guide to Ballad", chars: ["Aether", "Lumine", "Albedo", "Fischl", "Kaeya", "Lisa", "Rosaria", "Venti"]},
    { item: "Philosophies of Ballad", chars: ["Aether", "Lumine", "Albedo", "Fischl", "Kaeya", "Lisa", "Rosaria", "Venti"]},
    { item: "Teachings of Prosperity", chars: ["Keqing", "Ningguang", "Qiqi", "Shenhe", "Xiao", "Yelan"]},
    { item: "Guide to Prosperity", chars: ["Aether", "Lumine", "Keqing", "Ningguang", "Qiqi", "Shenhe", "Xiao", "Yelan"]},
    { item: "Philosophies of Prosperity", chars: ["Aether", "Lumine", "Keqing", "Ningguang", "Qiqi", "Shenhe", "Xiao", "Yelan"]},
    { item: "Teachings of Diligence", chars: ["Aether", "Lumine", "Chongyun", "Ganyu", "Hu Tao", "Kazuha", "Xiangling", "Yaoyao", "Yun Jin"]},
    { item: "Guide to Diligence", chars: ["Aether", "Lumine", "Chongyun", "Ganyu", "Hu Tao", "Kazuha", "Xiangling", "Yaoyao", "Yun Jin"]},
    { item: "Philosophies of Diligence", chars: ["Aether", "Lumine", "Chongyun", "Ganyu", "Hu Tao", "Kazuha", "Xiangling", "Yaoyao", "Yun Jin"]},
    { item: "Teachings of Gold", chars: ["Beidou", "Xingqiu", "Xinyan", "Yanfei", "Zhongli"]},
    { item: "Guide to Gold", chars: ["Aether", "Lumine", "Beidou", "Xingqiu", "Xinyan", "Yanfei", "Zhongli"]},
    { item: "Philosophies of Gold", chars: ["Aether", "Lumine", "Beidou", "Xingqiu", "Xinyan", "Yanfei", "Zhongli"]},
    { item: "Teachings of Transience", chars: ["Aether", "Lumine", "Heizou", "Kokomi", "Thoma", "Yoimiya"]},
    { item: "Guide to Transience", chars: ["Aether", "Lumine", "Heizou", "Kokomi", "Thoma", "Yoimiya"]},
    { item: "Philosophies of Transience", chars: ["Aether", "Lumine", "Heizou", "Kokomi", "Thoma", "Yoimiya"]},
    { item: "Teachings of Elegance", chars: ["Ayaka", "Ayato", "Itto", "Sara", "Shinobu"]},
    { item: "Guide to Elegance", chars: ["Aether", "Lumine", "Ayaka", "Ayato", "Itto", "Sara", "Shinobu"]},
    { item: "Philosophies of Elegance", chars: ["Aether", "Lumine", "Ayaka", "Ayato", "Itto", "Sara", "Shinobu"]},
    { item: "Teachings of Light", chars: ["Gorou", "Raiden", "Sayu", "Yae Miko"]},
    { item: "Guide to Light", chars: ["Aether", "Lumine", "Gorou", "Raiden", "Sayu", "Yae Miko"]},
    { item: "Philosophies of Light", chars: ["Aether", "Lumine", "Gorou", "Raiden", "Sayu", "Yae Miko"]},
    { item: "Teachings of Admonition", chars: ["Aether", "Lumine", "Cyno", "Faruzan", "Nilou", "Tighnari"]},
    { item: "Guide to Admonition", chars: ["Aether", "Lumine", "Cyno", "Faruzan", "Nilou", "Tighnari"]},
    { item: "Philosophies of Admonition", chars: ["Aether", "Lumine", "Cyno", "Faruzan", "Nilou", "Tighnari"]},
    { item: "Teachings of Ingenuity", chars: ["Alhaitham", "Dori", "Layla", "Nahida"]},
    { item: "Guide to Ingenuity", chars: ["Aether", "Lumine", "Alhaitham", "Dori", "Layla", "Nahida"]},
    { item: "Philosophies of Ingenuity", chars: ["Aether", "Lumine", "Alhaitham", "Dori", "Layla", "Nahida"]},
    { item: "Teachings of Praxis", chars: ["Candace", "Collei", "Wanderer"]},
    { item: "Guide to Praxis", chars: ["Aether", "Lumine", "Candace", "Collei", "Wanderer"]},
    { item: "Philosophies of Praxis", chars: ["Aether", "Lumine", "Candace", "Collei", "Wanderer"]},
]

export const talBossMats = [
    { item: "Dvalin's Plume", chars: ["Bennett", "Diluc", "Jean"]},
    { item: "Dvalin's Claw", chars: ["Lisa", "Noelle", "Razor", "Xiangling"]},
    { item: "Dvalin's Sigh", chars: ["Aether", "Lumine", "Amber", "Beidou", "Chongyun"]},
    { item: "Tail of Boreas", chars: ["Aether", "Lumine", "Qiqi", "Venti", "Xingqiu"]},
    { item: "Ring of Boreas", chars: ["Barbara", "Keqing", "Klee", "Mona"]},
    { item: "Spirit Locket of Boreas", chars: ["Fischl", "Kaeya", "Ningguang", "Sucrose"]},
    { item: "Tusk of Monoceros Caeli", chars: ["Albedo", "Xinyan", "Zhongli"]},
    { item: "Shard of a Foul Legacy", chars: ["Diona", "Hu Tao", "Tartaglia"]},
    { item: "Shadow of the Warrior", chars: ["Ganyu", "Rosaria", "Xiao"]},
    { item: "Dragon Lord's Crown", chars: ["Aether", "Lumine", "Eula", "Yoimiya"]},
    { item: "Bloodjade Branch", chars: ["Ayaka", "Dori", "Yanfei"]},
    { item: "Gilded Scale", chars: ["Kazuha", "Sayu", "Yelan"]},
    { item: "Molten Moment", chars: ["Aloy", "Gorou", "Raiden"]},
    { item: "Hellfire Butterfly", chars: ["Kokomi", "Shenhe", "Thoma"]},
    { item: "Ashen Heart", chars: ["Itto", "Sara", "Yun Jin"]},
    { item: "Mudra of the Malefic General", chars: ["Aether", "Lumine", "Ayato", "Cyno"]},
    { item: "Tears of the Calamitous God", chars: ["Candace", "Collei", "Nilou", "Shinobu"]},
    { item: "The Meaning of Aeons", chars: ["Heizou", "Tighnari", "Yae Miko"]},
    { item: "Puppet Strings", chars: ["Faruzan", "Nahida"]},
    { item: "Mirror of Mushin", chars: ["Alhaitham", "Layla"]},
    { item: "Daka's Bell", chars: ["Wanderer", "Yaoyao"]},
]

// Creating all the table data
function createData(item, amount, character, total) {
	return { item, amount, character, total };
}

export const gems = [
	createData("Agate Sliver", 0, 0, 0),
	createData("Agate Fragment", 0, 0, 0),
	createData("Agate Chunk", 0, 0, 0),
	createData("Agate Gemstone", 0, 0, 0),
	createData("Lazurite Sliver", 0, 0, 0),
	createData("Lazurite Fragment", 0, 0, 0),
	createData("Lazurite Chunk", 0, 0, 0),
	createData("Lazurite Gemstone", 0, 0, 0),
	createData("Amethyst Sliver", 0, 0, 0),
	createData("Amethyst Fragment", 0, 0, 0),
	createData("Amethyst Chunk", 0, 0, 0),
	createData("Amethyst Gemstone", 0, 0, 0),
	createData("Turquoise Sliver", 0, 0, 0),
	createData("Turquoise Fragment", 0, 0, 0),
	createData("Turquoise Chunk", 0, 0, 0),
	createData("Turquoise Gemstone", 0, 0, 0),
	createData("Jade Sliver", 0, 0, 0),
	createData("Jade Fragment", 0, 0, 0),
	createData("Jade Chunk", 0, 0, 0),
	createData("Jade Gemstone", 0, 0, 0),
	createData("Topaz Sliver", 0, 0, 0),
	createData("Topaz Fragment", 0, 0, 0),
	createData("Topaz Chunk", 0, 0, 0),
	createData("Topaz Gemstone", 0, 0, 0),
	createData("Emerald Sliver", 0, 0, 0),
	createData("Emerald Fragment", 0, 0, 0),
	createData("Emerald Chunk", 0, 0, 0),
	createData("Emerald Gemstone", 0, 0, 0),
	createData("Brilliant Diamond Sliver", 0, 0, 0),
	createData("Brilliant Diamond Fragment", 0, 0, 0),
	createData("Brilliant Diamond Chunk", 0, 0, 0),
	createData("Brilliant Diamond Gemstone", 0, 0, 0),
];

export const localSpecialtyList = [
	createData("Calla Lily", 0, 0, 0),
	createData("Wolfhook", 0, 0, 0),
	createData("Valberry", 0, 0, 0),
	createData("Cecilia", 0, 0, 0),
	createData("Windwheel Aster", 0, 0, 0),
	createData("Philanemo Mushroom", 0, 0, 0),
	createData("Jueyun Chili", 0, 0, 0),
	createData("Noctilucous Jade", 0, 0, 0),
	createData("Silk Flower", 0, 0, 0),
	createData("Glaze Lily", 0, 0, 0),
	createData("Qingxin", 0, 0, 0),
	createData("Starconch", 0, 0, 0),
	createData("Violetgrass", 0, 0, 0),
	createData("Small Lamp Grass", 0, 0, 0),
	createData("Dandelion Seed", 0, 0, 0),
	createData("Cor Lapis", 0, 0, 0),
	createData("Onikabuto", 0, 0, 0),
	createData("Sakura Bloom", 0, 0, 0),
	createData("Crystal Marrow", 0, 0, 0),
	createData("Dendrobrium", 0, 0, 0),
	createData("Naku Weed", 0, 0, 0),
	createData("Sea Ganoderma", 0, 0, 0),
	createData("Sango Pearl", 0, 0, 0),
	createData("Amakumo Fruit", 0, 0, 0),
	createData("Fluorescent Fungus", 0, 0, 0),
	createData("Rukkhashava Mushrooms", 0, 0, 0),
	createData("Padisarah", 0, 0, 0),
	createData("Nilotpala Lotus", 0, 0, 0),
	createData("Kalpalata Lotus", 0, 0, 0),
	createData("Redcrest", 0, 0, 0),
	createData("Sand Grease Pupa", 0, 0, 0),
	createData("Scarab", 0, 0, 0),
];

export const commonList = [
	createData("Slime Condensate", 0, 0, 0),
	createData("Slime Secretions", 0, 0, 0),
	createData("Slime Concentrate", 0, 0, 0),
	createData("Damaged Mask", 0, 0, 0),
	createData("Stained Mask", 0, 0, 0),
	createData("Ominous Mask", 0, 0, 0),
	createData("Divining Scroll", 0, 0, 0),
	createData("Sealed Scroll", 0, 0, 0),
	createData("Forbidden Scroll", 0, 0, 0),
	createData("Firm Arrowhead", 0, 0, 0),
	createData("Sharp Arrowhead", 0, 0, 0),
	createData("Weathered Arrowhead", 0, 0, 0),
	createData("Recruit's Insignia", 0, 0, 0),
	createData("Sergeant's Insignia", 0, 0, 0),
	createData("Lieutenant's Insignia", 0, 0, 0),
	createData("Treasure Hoarder Insignia", 0, 0, 0),
	createData("Silver Raven Insignia", 0, 0, 0),
	createData("Golden Raven Insignia", 0, 0, 0),
	createData("Whopperflower Nectar", 0, 0, 0),
	createData("Shimmering Nectar", 0, 0, 0),
	createData("Energy Nectar", 0, 0, 0),
	createData("Old Handguard", 0, 0, 0),
	createData("Kageuchi Handguard", 0, 0, 0),
	createData("Famed Handguard", 0, 0, 0),
	createData("Spectral Husk", 0, 0, 0),
	createData("Spectral Heart", 0, 0, 0),
	createData("Spectral Nucleus", 0, 0, 0),
	createData("Fungal Spores", 0, 0, 0),
	createData("Luminescent Pollen", 0, 0, 0),
	createData("Crystalline Cyst Dust", 0, 0, 0),
	createData("Faded Red Satin", 0, 0, 0),
	createData("Trimmed Red Silk", 0, 0, 0),
	createData("Rich Red Brocade", 0, 0, 0),
]

export const bossList = [
	createData("Hurricane Seed", 0, 0, 0),
	createData("Lightning Prism", 0, 0, 0),
	createData("Basalt Pillar", 0, 0, 0),
	createData("Hoarfrost Core", 0, 0, 0),
	createData("Everflame Seed", 0, 0, 0),
	createData("Cleansing Heart", 0, 0, 0),
	createData("Juvenile Jade", 0, 0, 0),
	createData("Crystalline Bloom", 0, 0, 0),
	createData("Marionette Core", 0, 0, 0),
	createData("Perpetual Heart", 0, 0, 0),
	createData("Smoldering Pearl", 0, 0, 0),
	createData("Dew of Repudiation", 0, 0, 0),
	createData("Storm Beads", 0, 0, 0),
	createData("Riftborn Regalia", 0, 0, 0),
	createData("Dragonheir's False Fin", 0, 0, 0),
	createData("Runic Fang", 0, 0, 0),
	createData("Majestic Hooked Beak", 0, 0, 0),
	createData("Thunderclap Fruitcore", 0, 0, 0),
	createData("Perpetual Caliber", 0, 0, 0),
	createData("Light Guiding Tetrahedron", 0, 0, 0),
	createData("Quelled Creeper", 0, 0, 0),
	createData("Pseudo Stamens", 0, 0, 0),
]

export const bookList = [
	createData("Teachings of Freedom", 0, 0, 0),
	createData("Guide to Freedom", 0, 0, 0),
	createData("Philosophies of Freedom", 0, 0, 0),
	createData("Teachings of Resistance", 0, 0, 0),
	createData("Guide to Resistance", 0, 0, 0),
	createData("Philosophies of Resistance", 0, 0, 0),
	createData("Teachings of Ballad", 0, 0, 0),
	createData("Guide to Ballad", 0, 0, 0),
	createData("Philosophies of Ballad", 0, 0, 0),
	createData("Teachings of Prosperity", 0, 0, 0),
	createData("Guide to Prosperity", 0, 0, 0),
	createData("Philosophies of Prosperity", 0, 0, 0),
	createData("Teachings of Diligence", 0, 0, 0),
	createData("Guide to Diligence", 0, 0, 0),
	createData("Philosophies of Diligence", 0, 0, 0),
	createData("Teachings of Gold", 0, 0, 0),
	createData("Guide to Gold", 0, 0, 0),
	createData("Philosophies of Gold", 0, 0, 0),
	createData("Teachings of Transience", 0, 0, 0),
	createData("Guide to Transience", 0, 0, 0),
	createData("Philosophies of Transience", 0, 0, 0),
	createData("Teachings of Elegance", 0, 0, 0),
	createData("Guide to Elegance", 0, 0, 0),
	createData("Philosophies of Elegance", 0, 0, 0),
	createData("Teachings of Light", 0, 0, 0),
	createData("Guide to Light", 0, 0, 0),
	createData("Philosophies of Light", 0, 0, 0),
	createData("Teachings of Admonition", 0, 0, 0),
	createData("Guide to Admonition", 0, 0, 0),
	createData("Philosophies of Admonition", 0, 0, 0),
	createData("Teachings of Ingenuity", 0, 0, 0),
	createData("Guide to Ingenuity", 0, 0, 0),
	createData("Philosophies of Ingenuity", 0, 0, 0),
	createData("Teachings of Praxis", 0, 0, 0),
	createData("Guide to Praxis", 0, 0, 0),
	createData("Philosophies of Praxis", 0, 0, 0),
]

export const talBossList = [
	createData("Dvalin's Plume", 0, 0, 0),
	createData("Dvalin's Claw", 0, 0, 0),
	createData("Dvalin's Sigh", 0, 0, 0),
	createData("Tail of Boreas", 0, 0, 0),
	createData("Ring of Boreas", 0, 0, 0),
	createData("Spirit Locket of Boreas", 0, 0, 0),
	createData("Tusk of Monoceros Caeli", 0, 0, 0),
	createData("Shard of a Foul Legacy", 0, 0, 0),
	createData("Shadow of the Warrior", 0, 0, 0),
	createData("Dragon Lord's Crown", 0, 0, 0),
	createData("Bloodjade Branch", 0, 0, 0),
	createData("Gilded Scale", 0, 0, 0),
	createData("Molten Moment", 0, 0, 0),
	createData("Hellfire Butterfly", 0, 0, 0),
	createData("Ashen Heart", 0, 0, 0),
	createData("Mudra of the Malefic General", 0, 0, 0),
	createData("Tears of the Calamitous God", 0, 0, 0),	
	createData("The Meaning of Aeons", 0, 0, 0),
	createData("Puppet Strings", 0, 0, 0),
	createData("Mirror of Mushin", 0, 0, 0),	
	createData("Daka's Bell", 0, 0, 0),
]

export const crownList = [
	createData("Crown of Sagehood", 0, 0, 0)
]