export const gemChars = [
    { item: "Agate Sliver", chars: ["Amber", "Bennett", "Diluc", "Klee", "Hu Tao", "Thoma", "Xiangling", "Xinyan", "Yanfei", "Yoimiya"]},
    { item: "Agate Fragment", chars: ["Amber", "Bennett", "Diluc", "Klee", "Hu Tao", "Thoma", "Xiangling", "Xinyan", "Yanfei", "Yoimiya"]},
    { item: "Agate Chunk", chars: ["Amber", "Bennett", "Diluc", "Klee", "Hu Tao", "Thoma", "Xiangling", "Xinyan", "Yanfei", "Yoimiya"]},
    { item: "Agate Gemstone", chars: ["Amber", "Bennett", "Diluc", "Klee", "Hu Tao", "Thoma", "Xiangling", "Xinyan", "Yanfei", "Yoimiya"]},
    { item: "Lazurite Sliver", chars: ["Ayato", "Barbara", "Kokomi", "Mona", "Tartaglia", "Xingqiu", "Yelan"]},
    { item: "Lazurite Fragment", chars: ["Ayato", "Barbara", "Kokomi", "Mona", "Tartaglia", "Xingqiu", "Yelan"]},
    { item: "Lazurite Chunk", chars: ["Ayato", "Barbara", "Kokomi", "Mona", "Tartaglia", "Xingqiu", "Yelan"]},
    { item: "Lazurite Gemstone", chars: ["Barbara", "Kokomi", "Mona", "Tartaglia", "Xingqiu", "Yelan"]},
    { item: "Amethyst Sliver", chars: ["Beidou", "Dori", "Fischl", "Keqing", "Lisa", "Raiden", "Razor", "Sara", "Shinobu", "Yae Miko"]},
    { item: "Amethyst Fragment", chars: ["Beidou", "Dori", "Fischl", "Keqing", "Lisa", "Raiden", "Razor", "Sara", "Shinobu", "Yae Miko"]},
    { item: "Amethyst Chunk", chars: ["Beidou", "Dori", "Fischl", "Keqing", "Lisa", "Raiden", "Razor", "Sara", "Shinobu", "Yae Miko"]},
    { item: "Amethyst Gemstone", chars: ["Beidou", "Dori", "Fischl", "Keqing", "Lisa", "Raiden", "Razor", "Sara", "Shinobu", "Yae Miko"]},
    { item: "Turquoise Sliver", chars: ["Heizou", "Jean", "Kazuha", "Sayu", "Sucrose", "Venti", "Xiao"]},
    { item: "Turquoise Fragment", chars: ["Heizou", "Jean", "Kazuha", "Sayu", "Sucrose", "Venti", "Xiao"]},
    { item: "Turquoise Chunk", chars: ["Heizou", "Jean", "Kazuha", "Sayu", "Sucrose", "Venti", "Xiao"]},
    { item: "Turquoise Gemstone", chars: ["Heizou", "Jean", "Kazuha", "Sayu", "Sucrose", "Venti", "Xiao"]},
    { item: "Jade Sliver", chars: ["Aloy", "Ayaka", "Chongyun", "Diona", "Eula", "Ganyu", "Kaeya", "Qiqi", "Rosaria", "Shenhe"]},
    { item: "Jade Fragment", chars: ["Aloy", "Ayaka", "Chongyun", "Diona", "Eula", "Ganyu", "Kaeya", "Qiqi", "Rosaria", "Shenhe"]},
    { item: "Jade Chunk", chars: ["Aloy", "Ayaka", "Chongyun", "Diona", "Eula", "Ganyu", "Kaeya", "Qiqi", "Rosaria", "Shenhe"]},
    { item: "Jade Gemstone", chars: ["Aloy", "Ayaka", "Chongyun", "Diona", "Eula", "Ganyu", "Kaeya", "Qiqi", "Rosaria", "Shenhe"]},
    { item: "Topaz Sliver", chars: ["Albedo", "Gorou", "Itto", "Ningguang", "Noelle", "Yun Jin", "Zhongli"]},
    { item: "Topaz Fragment", chars: ["Albedo", "Gorou", "Itto", "Ningguang", "Noelle", "Yun Jin", "Zhongli"]},
    { item: "Topaz Chunk", chars: ["Albedo", "Gorou", "Itto", "Ningguang", "Noelle", "Yun Jin", "Zhongli"]},
    { item: "Topaz Gemstone", chars: ["Albedo", "Gorou", "Itto", "Ningguang", "Noelle", "Yun Jin", "Zhongli"]},
    { item: "Emerald Sliver", chars: ["Collei", "Tighnari"]},
    { item: "Emerald Fragment", chars: ["Collei", "Tighnari"]},
    { item: "Emerald Chunk", chars: ["Collei", "Tighnari"]},
    { item: "Emerald Gemstone", chars: ["Collei", "Tighnari"]},
    { item: "Brilliant Diamond Sliver", chars: ["Aether", "Lumine"]},
    { item: "Brilliant Diamond Fragment", chars: ["Aether", "Lumine"]},
    { item: "Brilliant Diamond Chunk", chars: ["Aether", "Lumine"]},
    { item: "Brilliant Diamond Gemstone", chars: ["Aether", "Lumine"]}
]

export const localSpecialties = [
    { item: "Calla Lily", chars: ["Diona", "Kaeya"]},
    { item: "Wolfhook", chars: ["Razor"]},
    { item: "Valberry", chars: ["Lisa", "Noelle", "Rosaria"]},
    { item: "Cecilia", chars: ["Albedo", "Venti"]},
    { item: "Windwheel Aster", chars: ["Aether", "Lumine", "Bennett", "Sucrose"]},
    { item: "Philanemo Mushroom", chars: ["Barbara", "Klee", "Mona"]},
    { item: "Jueyun Chili", chars: ["Xiangling"]},
    { item: "Noctilucous Jade", chars: ["Beidou", "Yanfei"]},
    { item: "Silk Flower", chars: ["Hu Tao", "Xingqiu"]},
    { item: "Glaze Lily", chars: ["Ningguang", "Yun Jin"]},
    { item: "Qingxin", chars: ["Ganyu", "Shenhe", "Xiao"]},
    { item: "Starconch", chars: ["Tartaglia", "Yelan"]},
    { item: "Violetgrass", chars: ["Qiqi", "Xinyan"]},
    { item: "Small Lamp Grass", chars: ["Amber", "Diluc", "Fischl"]},
    { item: "Dandelion Seed", chars: ["Eula", "Jean"]},
    { item: "Cor Lapis", chars: ["Chongyun", "Keqing", "Zhongli"]},
    { item: "Onikabuto", chars: ["Heizou", "Itto"]},
    { item: "Sakura Bloom", chars: ["Ayaka", "Ayato"]},
    { item: "Crystal Marrow", chars: ["Aloy", "Sayu"]},
    { item: "Dendrobrium", chars: ["Sara"]},
    { item: "Naku Weed", chars: ["Shinobu", "Yoimiya"]},
    { item: "Sea Ganoderma", chars: ["Kazuha", "Yae Miko"]},
    { item: "Sango Pearl", chars: ["Gorou", "Kokomi"]},
    { item: "Amakumo Fruit", chars: ["Raiden"]},
    { item: "Fluorescent Fungus", chars: ["Thoma"]},
    { item: "Sumeru Rose", chars: []},
    { item: "Padisarah", chars: []},
    { item: "Zaytun Peach", chars: []},
    { item: "Harra Fruit", chars: []},
    { item: "Viboya", chars: []},
    { item: "Kalpalata Lotus", chars: ["Dori"]},
    { item: "Nilotpala Lotus", chars: ["Tighnari"]},
    { item: "Rukkhashava Mushrooms", chars: ["Collei"]},
]

export const commons = [
    { item: "Slime Condensate", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Zhongli"] },
    { item: "Slime Secretions", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Zhongli"] },
    { item: "Slime Concentrate", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Zhongli"] },
    { item: "Damaged Mask", chars: ["Aether", "Chongyun", "Eula", "Jean", "Lumine", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Stained Mask", chars: ["Aether", "Chongyun", "Eula", "Jean", "Lumine", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Ominous Mask", chars: ["Aether", "Chongyun", "Eula", "Jean", "Lumine", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Divining Scroll", chars: ["Albedo", "Barbara", "Klee", "Qiqi", "Yoimiya"] },
    { item: "Sealed Scroll", chars: ["Albedo", "Barbara", "Klee", "Qiqi", "Yoimiya"] },
    { item: "Forbidden Scroll", chars: ["Albedo", "Barbara", "Klee", "Qiqi", "Yoimiya"] },
    { item: "Firm Arrowhead", chars: ["Amber", "Collei", "Diona", "Fischl"] },
    { item: "Sharp Arrowhead", chars: ["Amber", "Collei", "Diona", "Fischl"] },
    { item: "Weathered Arrowhead", chars: ["Amber", "Collei", "Diona", "Fischl"] },
    { item: "Recruit's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia", "Yelan"] },
    { item: "Sergeant's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia", "Yelan"] },
    { item: "Lieutenant's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia", "Yelan"] },
    { item: "Treasure Hoarder Insignia", chars: ["Beidou", "Bennett", "Heizou", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Silver Raven Insignia", chars: ["Beidou", "Bennett", "Heizou", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Golden Raven Insignia", chars: ["Beidou", "Bennett", "Heizou", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Whopperflower Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Shimmering Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Energy Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Old Handguard", chars: ["Ayaka", "Ayato", "Raiden", "Yae Miko"] },
    { item: "Kageuchi Handguard", chars: ["Ayaka", "Ayato", "Raiden", "Yae Miko"] },
    { item: "Famed Handguard", chars: ["Ayaka", "Ayato", "Raiden", "Yae Miko"] },
    { item: "Spectral Husk", chars: ["Aloy", "Gorou", "Kokomi", "Shinobu"] },
    { item: "Spectral Heart", chars: ["Aloy", "Gorou", "Kokomi", "Shinobu"] },
    { item: "Spectral Nucleus", chars: ["Aloy", "Gorou", "Kokomi", "Shinobu"] },
    { item: "Fungal Spores", chars: ["Tighnari"] },
    { item: "Luminescent Pollen", chars: ["Tighnari"] },
    { item: "Crystalline Cyst Dust", chars: ["Tighnari"] },
    { item: "Faded Red Satin", chars: ["Dori"] },
    { item: "Trimmed Red Silk", chars: ["Dori"] },
    { item: "Rich Red Brocade", chars: ["Dori"] },
]

export const bossMats = [
    { item: "Hurricane Seed", chars: ["Jean", "Sucrose", "Venti"] },
    { item: "Lightning Prism", chars: ["Beidou", "Fischl", "Keqing", "Lisa", "Razor"] },
    { item: "Basalt Pillar", chars: ["Albedo", "Ningguang", "Noelle", "Zhongli"] },
    { item: "Hoarfrost Core", chars: ["Chongyun", "Diona", "Ganyu", "Kaeya", "Qiqi", "Rosaria"] },
    { item: "Everflame Seed", chars: ["Amber", "Bennett", "Diluc", "Klee", "Xiangling", "Xinyan"] },
    { item: "Cleansing Heart", chars: ["Barbara", "Mona", "Tartaglia", "Xingqiu"] },
    { item: "Juvenile Jade", chars: ["Hu Tao", "Xiao", "Yanfei"] },
    { item: "Crystalline Bloom", chars: ["Aloy", "Eula"] },
    { item: "Marionette Core", chars: ["Kazuha", "Sayu"] },
    { item: "Perpetual Heart", chars: ["Ayaka", "Gorou"] },
    { item: "Smoldering Pearl", chars: ["Thoma", "Yoimiya"] },
    { item: "Dew of Repudiation", chars: ["Ayato", "Kokomi"] },
    { item: "Storm Beads", chars: ["Raiden", "Sara"] },
    { item: "Riftborn Regalia", chars: ["Itto", "Yun Jin"] },
    { item: "Dragonheir's False Fin", chars: ["Shenhe", "Yae Miko"] },
    { item: "Runic Fang", chars: ["Heizou", "Shinobu", "Yelan"] },
    { item: "Majestic Hooked Beak", chars: ["Collei", "Tighnari"] },
    { item: "Thunderclap Fruitcore", chars: ["Dori"] },
]

export const talCommon = [
    { item: "Slime Condensate", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Zhongli"] },
    { item: "Slime Secretions", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Zhongli"] },
    { item: "Slime Concentrate", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Zhongli"] },
    { item: "Damaged Mask", chars: ["Chongyun", "Eula", "Jean", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Stained Mask", chars: ["Chongyun", "Eula", "Jean", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Ominous Mask", chars: ["Chongyun", "Eula", "Jean", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Divining Scroll", chars: ["Aether", "Lumine", "Albedo", "Barbara", "Klee", "Qiqi", "Yoimiya"] },
    { item: "Sealed Scroll", chars: ["Aether", "Lumine", "Albedo", "Barbara", "Klee", "Qiqi", "Yoimiya"] },
    { item: "Forbidden Scroll", chars: ["Aether", "Lumine", "Albedo", "Barbara", "Klee", "Qiqi", "Yoimiya"] },
    { item: "Firm Arrowhead", chars: ["Aether", "Lumine", "Amber", "Collei", "Diona", "Fischl"] },
    { item: "Sharp Arrowhead", chars: ["Aether", "Lumine", "Amber", "Collei", "Diona", "Fischl"] },
    { item: "Weathered Arrowhead", chars: ["Aether", "Lumine", "Amber", "Collei", "Diona", "Fischl"] },
    { item: "Recruit's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia", "Yelan"] },
    { item: "Sergeant's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia", "Yelan"] },
    { item: "Lieutenant's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia", "Yelan"] },
    { item: "Treasure Hoarder Insignia", chars: ["Beidou", "Bennett", "Heizou", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Silver Raven Insignia", chars: ["Beidou", "Bennett", "Heizou", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Golden Raven Insignia", chars: ["Beidou", "Bennett", "Heizou", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Whopperflower Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Shimmering Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Energy Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Old Handguard", chars: ["Aether", "Lumine", "Ayaka", "Ayato", "Raiden", "Yae Miko"] },
    { item: "Kageuchi Handguard", chars: ["Aether", "Lumine", "Ayaka", "Ayato", "Raiden", "Yae Miko"] },
    { item: "Famed Handguard", chars: ["Aether", "Lumine", "Ayaka", "Ayato", "Raiden", "Yae Miko"] },
    { item: "Spectral Husk", chars: ["Aloy", "Gorou", "Kokomi", "Shinobu"] },
    { item: "Spectral Heart", chars: ["Aloy", "Gorou", "Kokomi", "Shinobu"] },
    { item: "Spectral Nucleus", chars: ["Aloy", "Gorou", "Kokomi", "Shinobu"] },
    { item: "Fungal Spores", chars: ["Tighnari"] },
    { item: "Luminescent Pollen", chars: ["Tighnari"] },
    { item: "Crystalline Cyst Dust", chars: ["Tighnari"] },
    { item: "Faded Red Satin", chars: ["Dori"] },
    { item: "Trimmed Red Silk", chars: ["Dori"] },
    { item: "Rich Red Brocade", chars: ["Dori"] },
]

export const crowns = [
    { item: "Crown of Sagehood", chars: ["Aether", "Lumine", "Albedo", "Aloy", "Amber", "Ayaka", "Ayato", "Barbara", "Beidou", "Bennett", "Chongyun", "Collei", "Diluc", "Diona", "Dori", "Eula", "Fischl", "Ganyu", "Gorou", "Heizou", "Hu Tao", "Itto", "Jean", "Kaeya", "Kazuha", "Keqing", "Klee", "Kokomi", "Shinobu", "Lisa", "Mona", "Ningguang", "Noelle", "Qiqi", "Raiden", "Razor", "Rosaria", "Sara", "Sayu", "Shenhe", "Sucrose", "Tartaglia", "Thoma", "Tighnari", "Venti", "Xiao", "Xiangling", "Xingqiu", "Xinyan", "Yae Miko", "Yanfei", "Yelan", "Yoimiya", "Yun Jin", "Zhongli"]}
]

export const books = [
    { item: "Teachings of Freedom", chars: ["Aether", "Lumine", "Aloy", "Amber", "Barbara", "Diona", "Klee", "Sucrose", "Tartaglia"]},
    { item: "Guide to Freedom", chars: ["Aether", "Lumine", "Aloy", "Amber", "Barbara", "Diona", "Klee", "Sucrose", "Tartaglia"]},
    { item: "Philosophies of Freedom", chars: ["Aether", "Lumine", "Aloy", "Amber", "Barbara", "Diona", "Klee", "Sucrose", "Tartaglia"]},
    { item: "Teachings of Resistance", chars: ["Bennett", "Diluc", "Eula", "Jean", "Mona", "Noelle", "Razor"]},
    { item: "Guide to Resistance", chars: ["Aether", "Lumine", "Bennett", "Diluc", "Eula", "Jean", "Mona", "Noelle", "Razor"]},
    { item: "Philosophies of Resistance", chars: ["Aether", "Lumine", "Bennett", "Diluc", "Eula", "Jean", "Mona", "Noelle", "Razor"]},
    { item: "Teachings of Ballad", chars: ["Albedo", "Fischl", "Kaeya", "Lisa", "Rosaria", "Venti"]},
    { item: "Guide to Ballad", chars: ["Aether", "Lumine", "Albedo", "Fischl", "Kaeya", "Lisa", "Rosaria", "Venti"]},
    { item: "Philosophies of Ballad", chars: ["Aether", "Lumine", "Albedo", "Fischl", "Kaeya", "Lisa", "Rosaria", "Venti"]},
    { item: "Teachings of Prosperity", chars: ["Keqing", "Ningguang", "Qiqi", "Shenhe", "Xiao", "Yelan"]},
    { item: "Guide to Prosperity", chars: ["Aether", "Lumine", "Keqing", "Ningguang", "Qiqi", "Shenhe", "Xiao", "Yelan"]},
    { item: "Philosophies of Prosperity", chars: ["Aether", "Lumine", "Keqing", "Ningguang", "Qiqi", "Shenhe", "Xiao", "Yelan"]},
    { item: "Teachings of Diligence", chars: ["Aether", "Lumine", "Chongyun", "Ganyu", "Hu Tao", "Kazuha", "Xiangling", "Yun Jin"]},
    { item: "Guide to Diligence", chars: ["Aether", "Lumine", "Chongyun", "Ganyu", "Hu Tao", "Kazuha", "Xiangling", "Yun Jin"]},
    { item: "Philosophies of Diligence", chars: ["Aether", "Lumine", "Chongyun", "Ganyu", "Hu Tao", "Kazuha", "Xiangling", "Yun Jin"]},
    { item: "Teachings of Gold", chars: ["Beidou", "Xingqiu", "Xinyan", "Yanfei", "Zhongli"]},
    { item: "Guide to Gold", chars: ["Aether", "Lumine", "Beidou", "Xingqiu", "Xinyan", "Yanfei", "Zhongli"]},
    { item: "Philosophies of Gold", chars: ["Aether", "Lumine", "Beidou", "Xingqiu", "Xinyan", "Yanfei", "Zhongli"]},
    { item: "Teachings of Transience", chars: ["Aether", "Lumine", "Heizou", "Kokomi", "Thoma", "Yoimiya"]},
    { item: "Guide to Transience", chars: ["Aether", "Lumine", "Heizou", "Kokomi", "Thoma", "Yoimiya"]},
    { item: "Philosophies of Transience", chars: ["Aether", "Lumine", "Heizou", "Kokomi", "Thoma", "Yoimiya"]},
    { item: "Teachings of Elegance", chars: ["Ayaka", "Ayato", "Itto", "Sara", "Shinobu"]},
    { item: "Guide to Elegance", chars: ["Aether", "Lumine", "Ayaka", "Ayato", "Itto", "Sara", "Shinobu"]},
    { item: "Philosophies of Elegance", chars: ["Aether", "Lumine", "Ayaka", "Ayato", "Itto", "Sara", "Shinobu"]},
    { item: "Teachings of Light", chars: ["Gorou", "Raiden", "Sayu", "Yae Miko"]},
    { item: "Guide to Light", chars: ["Aether", "Lumine", "Gorou", "Raiden", "Sayu", "Yae Miko"]},
    { item: "Philosophies of Light", chars: ["Aether", "Lumine", "Gorou", "Raiden", "Sayu", "Yae Miko"]},
    { item: "Teachings of Admonition", chars: ["Aether", "Lumine", "Tighnari"]},
    { item: "Guide to Admonition", chars: ["Aether", "Lumine", "Tighnari"]},
    { item: "Philosophies of Admonition", chars: ["Aether", "Lumine", "Tighnari"]},
    { item: "Teachings of Ingenuity", chars: ["Dori"]},
    { item: "Guide to Ingenuity", chars: ["Aether", "Lumine", "Dori"]},
    { item: "Philosophies of Ingenuity", chars: ["Aether", "Lumine", "Dori"]},
    { item: "Teachings of Praxis", chars: ["Collei"]},
    { item: "Guide to Praxis", chars: ["Aether", "Lumine", "Collei"]},
    { item: "Philosophies of Praxis", chars: ["Aether", "Lumine", "Collei"]},
]

export const talBossMats = [
    { item: "Dvalin's Plume", chars: ["Bennett", "Diluc", "Jean"]},
    { item: "Dvalin's Claw", chars: ["Lisa", "Noelle", "Razor", "Xiangling"]},
    { item: "Dvalin's Sigh", chars: ["Aether", "Lumine", "Amber", "Beidou", "Chongyun"]},
    { item: "Tail of Boreas", chars: ["Aether", "Lumine", "Qiqi", "Venti", "Xingqiu"]},
    { item: "Ring of Boreas", chars: ["Barbara", "Keqing", "Klee", "Mona"]},
    { item: "Spirit Locket of Boreas", chars: ["Fischl", "Kaeya", "Ningguang", "Sucrose"]},
    { item: "Tusk of Monoceros Caeli", chars: ["Albedo", "Xinyan", "Zhongli"]},
    { item: "Shard of a Foul Legacy", chars: ["Diona", "Hu Tao", "Tartaglia"]},
    { item: "Shadow of the Warrior", chars: ["Ganyu", "Rosaria", "Xiao"]},
    { item: "Dragon Lord's Crown", chars: ["Aether", "Lumine", "Eula", "Yoimiya"]},
    { item: "Bloodjade Branch", chars: ["Ayaka", "Yanfei"]},
    { item: "Gilded Scale", chars: ["Kazuha", "Sayu", "Yelan"]},
    { item: "Molten Moment", chars: ["Aloy", "Gorou", "Raiden"]},
    { item: "Hellfire Butterfly", chars: ["Kokomi", "Shenhe", "Thoma"]},
    { item: "Ashen Heart", chars: ["Itto", "Sara", "Yun Jin"]},
    { item: "Mudra of the Malefic General", chars: ["Ayato"]},
    { item: "Tears of the Calamitous God", chars: ["Shinobu"]},
    { item: "The Meaning of Aeons", chars: ["Heizou", "Yae Miko"]},
]