export const gemChars = [
    { item: "Agate Sliver", chars: ["Amber", "Bennett", "Diluc", "Klee", "Hu Tao", "Thoma", "Xiangling", "Xinyan", "Yanfei", "Yoimiya"]},
    { item: "Agate Fragment", chars: ["Amber", "Bennett", "Diluc", "Klee", "Hu Tao", "Thoma", "Xiangling", "Xinyan", "Yanfei", "Yoimiya"]},
    { item: "Agate Chunk", chars: ["Amber", "Bennett", "Diluc", "Klee", "Hu Tao", "Thoma", "Xiangling", "Xinyan", "Yanfei", "Yoimiya"]},
    { item: "Agate Gemstone", chars: ["Amber", "Bennett", "Diluc", "Klee", "Hu Tao", "Thoma", "Xiangling", "Xinyan", "Yanfei", "Yoimiya"]},
    { item: "Lazurite Sliver", chars: ["Barbara", "Kokomi", "Mona", "Tartaglia", "Xingqiu"]},
    { item: "Lazurite Fragment", chars: ["Barbara", "Kokomi", "Mona", "Tartaglia", "Xingqiu"]},
    { item: "Lazurite Chunk", chars: ["Barbara", "Kokomi", "Mona", "Tartaglia", "Xingqiu"]},
    { item: "Lazurite Gemstone", chars: ["Barbara", "Kokomi", "Mona", "Tartaglia", "Xingqiu"]},
    { item: "Amethyst Sliver", chars: ["Beidou", "Fischl", "Keqing", "Lisa", "Raiden", "Razor", "Sara", "Yae Miko"]},
    { item: "Amethyst Fragment", chars: ["Beidou", "Fischl", "Keqing", "Lisa", "Raiden", "Razor", "Sara", "Yae Miko"]},
    { item: "Amethyst Chunk", chars: ["Beidou", "Fischl", "Keqing", "Lisa", "Raiden", "Razor", "Sara", "Yae Miko"]},
    { item: "Amethyst Gemstone", chars: ["Beidou", "Fischl", "Keqing", "Lisa", "Raiden", "Razor", "Sara", "Yae Miko"]},
    { item: "Turquoise Sliver", chars: ["Jean", "Kazuha", "Sayu", "Sucrose", "Venti", "Xiao"]},
    { item: "Turquoise Fragment", chars: ["Jean", "Kazuha", "Sayu", "Sucrose", "Venti", "Xiao"]},
    { item: "Turquoise Chunk", chars: ["Jean", "Kazuha", "Sayu", "Sucrose", "Venti", "Xiao"]},
    { item: "Turquoise Gemstone", chars: ["Jean", "Kazuha", "Sayu", "Sucrose", "Venti", "Xiao"]},
    { item: "Jade Sliver", chars: ["Aloy", "Ayaka", "Chongyun", "Diona", "Eula", "Ganyu", "Kaeya", "Qiqi", "Rosaria", "Shenhe"]},
    { item: "Jade Fragment", chars: ["Aloy", "Ayaka", "Chongyun", "Diona", "Eula", "Ganyu", "Kaeya", "Qiqi", "Rosaria", "Shenhe"]},
    { item: "Jade Chunk", chars: ["Aloy", "Ayaka", "Chongyun", "Diona", "Eula", "Ganyu", "Kaeya", "Qiqi", "Rosaria", "Shenhe"]},
    { item: "Jade Gemstone", chars: ["Aloy", "Ayaka", "Chongyun", "Diona", "Eula", "Ganyu", "Kaeya", "Qiqi", "Rosaria", "Shenhe"]},
    { item: "Topaz Sliver", chars: ["Albedo", "Gorou", "Itto", "Ningguang", "Noelle", "Yun Jin", "Zhongli"]},
    { item: "Topaz Fragment", chars: ["Albedo", "Gorou", "Itto", "Ningguang", "Noelle", "Yun Jin", "Zhongli"]},
    { item: "Topaz Chunk", chars: ["Albedo", "Gorou", "Itto", "Ningguang", "Noelle", "Yun Jin", "Zhongli"]},
    { item: "Topaz Gemstone", chars: ["Albedo", "Gorou", "Itto", "Ningguang", "Noelle", "Yun Jin", "Zhongli"]},
    // { item: "Emerald Sliver", chars: []},
    // { item: "Emerald Fragment", chars: []},
    // { item: "Emerald Chunk", chars: []},
    // { item: "Emerald Gemstone", chars: []},
    { item: "Brilliant Diamond Sliver", chars: ["Aether", "Lumine"]},
    { item: "Brilliant Diamond Fragment", chars: ["Aether", "Lumine"]},
    { item: "Brilliant Diamond Chunk", chars: ["Aether", "Lumine"]},
    { item: "Brilliant Diamond Gemstone", chars: ["Aether", "Lumine"]}
]

export const localSpecialties = [
    { item: "Calla Lily", chars: ["Diona", "Kaeya"]},
    { item: "Wolfhook", chars: ["Razor"]},
    { item: "Valberry", chars: ["Lisa", "Noelle", "Rosaria"]},
    { item: "Cecilia", chars: ["Albedo", "Venti"]},
    { item: "Windwheel Aster", chars: ["Aether", "Lumine", "Bennett", "Sucrose"]},
    { item: "Philanemo Mushroom", chars: ["Barbara", "Klee", "Mona"]},
    { item: "Jueyun Chili", chars: ["Xiangling"]},
    { item: "Noctilucous Jade", chars: ["Beidou", "Yanfei"]},
    { item: "Silk Flower", chars: ["Hu Tao", "Xingqiu"]},
    { item: "Glaze Lily", chars: ["Ningguang", "Yun Jin"]},
    { item: "Qingxin", chars: ["Ganyu", "Shenhe", "Xiao"]},
    { item: "Starconch", chars: ["Tartaglia"]},
    { item: "Violetgrass", chars: ["Qiqi", "Xinyan"]},
    { item: "Small Lamp Grass", chars: ["Amber", "Diluc", "Fischl"]},
    { item: "Dandelion Seed", chars: ["Eula", "Jean"]},
    { item: "Cor Lapis", chars: ["Chongyun", "Keqing", "Zhongli"]},
    { item: "Onikabuto", chars: ["Itto"]},
    { item: "Sakura Bloom", chars: ["Ayaka"]},
    { item: "Crystal Marrow", chars: ["Aloy", "Sayu"]},
    { item: "Dendrobrium", chars: ["Sara"]},
    { item: "Naku Weed", chars: ["Yoimiya"]},
    { item: "Sea Ganoderma", chars: ["Kazuha", "Yae Miko"]},
    { item: "Sango Pearl", chars: ["Gorou", "Kokomi"]},
    { item: "Amakumo Fruit", chars: ["Raiden"]},
    { item: "Fluorescent Fungus", chars: ["Thoma"]},
]

export const commons = [
    { item: "Slime Condensate", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Zhongli"] },
    { item: "Slime Secretions", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Zhongli"] },
    { item: "Slime Concentrate", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Zhongli"] },
    { item: "Damaged Mask", chars: ["Aether", "Chongyun", "Eula", "Jean", "Lumine", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Stained Mask", chars: ["Aether", "Chongyun", "Eula", "Jean", "Lumine", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Ominous Mask", chars: ["Aether", "Chongyun", "Eula", "Jean", "Lumine", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Divining Scroll", chars: ["Albedo", "Barbara", "Klee", "Qiqi", "Yoimiya"] },
    { item: "Sealed Scroll", chars: ["Albedo", "Barbara", "Klee", "Qiqi", "Yoimiya"] },
    { item: "Forbidden Scroll", chars: ["Albedo", "Barbara", "Klee", "Qiqi", "Yoimiya"] },
    { item: "Firm Arrowhead", chars: ["Amber", "Diona", "Fischl"] },
    { item: "Sharp Arrowhead", chars: ["Amber", "Diona", "Fischl"] },
    { item: "Weathered Arrowhead", chars: ["Amber", "Diona", "Fischl"] },
    { item: "Recruit's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia"] },
    { item: "Sergeant's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia"] },
    { item: "Lieutenant's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia"] },
    { item: "Treasure Hoarder Insignia", chars: ["Beidou", "Bennett", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Silver Raven Insignia", chars: ["Beidou", "Bennett", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Golden Raven Insignia", chars: ["Beidou", "Bennett", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Whopperflower Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Shimmering Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Energy Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Old Handguard", chars: ["Ayaka", "Raiden", "Yae Miko"] },
    { item: "Kageuchi Handguard", chars: ["Ayaka", "Raiden", "Yae Miko"] },
    { item: "Famed Handguard", chars: ["Ayaka", "Raiden", "Yae Miko"] },
    { item: "Spectral Husk", chars: ["Aloy", "Gorou", "Kokomi"] },
    { item: "Spectral Heart", chars: ["Aloy", "Gorou", "Kokomi"] },
    { item: "Spectral Nucleus", chars: ["Aloy", "Gorou", "Kokomi"] },
]

export const bossMats = [
    { item: "Hurricane Seed", chars: ["Jean", "Sucrose", "Venti"] },
    { item: "Lightning Prism", chars: ["Beidou", "Fischl", "Keqing", "Lisa", "Razor"] },
    { item: "Basalt Pillar", chars: ["Albedo", "Ningguang", "Noelle", "Zhongli"] },
    { item: "Hoarfrost Core", chars: ["Chongyun", "Diona", "Ganyu", "Kaeya", "Qiqi", "Rosaria"] },
    { item: "Everflame Seed", chars: ["Amber", "Bennett", "Diluc", "Klee", "Xiangling", "Xinyan"] },
    { item: "Cleansing Heart", chars: ["Barbara", "Mona", "Tartaglia", "Xingqiu"] },
    { item: "Juvenile Jade", chars: ["Hu Tao", "Xiao", "Yanfei"] },
    { item: "Crystalline Bloom", chars: ["Aloy", "Eula"] },
    { item: "Marionette Core", chars: ["Kazuha", "Sayu"] },
    { item: "Perpetual Heart", chars: ["Ayaka", "Gorou"] },
    { item: "Smoldering Pearl", chars: ["Thoma", "Yoimiya"] },
    { item: "Dew of Repudiation", chars: ["Kokomi"] },
    { item: "Storm Beads", chars: ["Raiden", "Sara"] },
    { item: "Riftborn Regalia", chars: ["Itto", "Yun Jin"] },
    { item: "Dragonheir's False Fin", chars: ["Shenhe", "Yae Miko"] },
]

export const talCommon = [
    { item: "Slime Condensate", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Zhongli"] },
    { item: "Slime Secretions", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Zhongli"] },
    { item: "Slime Concentrate", chars: ["Itto", "Lisa", "Venti", "Xiangling", "Xiao", "Zhongli"] },
    { item: "Damaged Mask", chars: ["Chongyun", "Eula", "Jean", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Stained Mask", chars: ["Chongyun", "Eula", "Jean", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Ominous Mask", chars: ["Chongyun", "Eula", "Jean", "Noelle", "Razor", "Sara", "Xingqiu", "Yun Jin"] },
    { item: "Divining Scroll", chars: ["Aether", "Lumine", "Albedo", "Barbara", "Klee", "Qiqi", "Yoimiya"] },
    { item: "Sealed Scroll", chars: ["Aether", "Lumine", "Albedo", "Barbara", "Klee", "Qiqi", "Yoimiya"] },
    { item: "Forbidden Scroll", chars: ["Aether", "Lumine", "Albedo", "Barbara", "Klee", "Qiqi", "Yoimiya"] },
    { item: "Firm Arrowhead", chars: ["Aether", "Lumine", "Amber", "Diona", "Fischl"] },
    { item: "Sharp Arrowhead", chars: ["Aether", "Lumine", "Amber", "Diona", "Fischl"] },
    { item: "Weathered Arrowhead", chars: ["Aether", "Lumine", "Amber", "Diona", "Fischl"] },
    { item: "Recruit's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia"] },
    { item: "Sergeant's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia"] },
    { item: "Lieutenant's Insignia", chars: ["Diluc", "Ningguang", "Rosaria", "Tartaglia"] },
    { item: "Treasure Hoarder Insignia", chars: ["Beidou", "Bennett", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Silver Raven Insignia", chars: ["Beidou", "Bennett", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Golden Raven Insignia", chars: ["Beidou", "Bennett", "Kaeya", "Kazuha", "Thoma", "Xinyan", "Yanfei"] },
    { item: "Whopperflower Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Shimmering Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Energy Nectar", chars: ["Ganyu", "Hu Tao", "Keqing", "Mona", "Sayu", "Shenhe", "Sucrose"] },
    { item: "Old Handguard", chars: ["Aether", "Lumine", "Ayaka", "Raiden", "Yae Miko"] },
    { item: "Kageuchi Handguard", chars: ["Aether", "Lumine", "Ayaka", "Raiden", "Yae Miko"] },
    { item: "Famed Handguard", chars: ["Aether", "Lumine", "Ayaka", "Raiden", "Yae Miko"] },
    { item: "Spectral Husk", chars: ["Aloy", "Gorou", "Kokomi"] },
    { item: "Spectral Heart", chars: ["Aloy", "Gorou", "Kokomi"] },
    { item: "Spectral Nucleus", chars: ["Aloy", "Gorou", "Kokomi"] },
]

export const crowns = [
    { item: "Crown of Sagehood", chars: ["Aether", "Lumine", "Albedo", "Aloy", "Amber", "Ayaka", "Barbara", "Beidou", "Bennett", "Chongyun", "Diluc", "Diona", "Eula", "Fischl", "Ganyu", "Gorou", "Hu Tao", "Itto", "Jean", "Kaeya", "Kazuha", "Keqing", "Klee", "Kokomi", "Lisa", "Mona", "Ningguang", "Noelle", "Qiqi", "Raiden", "Razor", "Rosaria", "Sara", "Sayu", "Shenhe", "Sucrose", "Tartaglia", "Thoma", "Venti", "Xiao", "Xiangling", "Xingqiu", "Xinyan", "Yae Miko", "Yanfei", "Yoimiya", "Yun Jin", "Zhongli"]}
]

export const books = [
    { item: "Teachings of Freedom", chars: ["Aether", "Lumine", "Aloy", "Amber", "Barbara", "Diona", "Klee", "Sucrose", "Tartaglia"]},
    { item: "Guide to Freedom", chars: ["Aether", "Lumine", "Aloy", "Amber", "Barbara", "Diona", "Klee", "Sucrose", "Tartaglia"]},
    { item: "Philosophies of Freedom", chars: ["Aether", "Lumine", "Aloy", "Amber", "Barbara", "Diona", "Klee", "Sucrose", "Tartaglia"]},
    { item: "Teachings of Resistance", chars: ["Bennett", "Diluc", "Eula", "Jean", "Mona", "Noelle", "Razor"]},
    { item: "Guide to Resistance", chars: ["Aether", "Lumine", "Bennett", "Diluc", "Eula", "Jean", "Mona", "Noelle", "Razor"]},
    { item: "Philosophies of Resistance", chars: ["Aether", "Lumine", "Bennett", "Diluc", "Eula", "Jean", "Mona", "Noelle", "Razor"]},
    { item: "Teachings of Ballad", chars: ["Albedo", "Fischl", "Kaeya", "Lisa", "Rosaria", "Venti"]},
    { item: "Guide to Ballad", chars: ["Aether", "Lumine", "Albedo", "Fischl", "Kaeya", "Lisa", "Rosaria", "Venti"]},
    { item: "Philosophies of Ballad", chars: ["Aether", "Lumine", "Albedo", "Fischl", "Kaeya", "Lisa", "Rosaria", "Venti"]},
    { item: "Teachings of Prosperity", chars: ["Keqing", "Ningguang", "Qiqi", "Shenhe", "Xiao"]},
    { item: "Guide to Prosperity", chars: ["Aether", "Lumine", "Keqing", "Ningguang", "Qiqi", "Shenhe", "Xiao"]},
    { item: "Philosophies of Prosperity", chars: ["Aether", "Lumine", "Keqing", "Ningguang", "Qiqi", "Shenhe", "Xiao"]},
    { item: "Teachings of Diligence", chars: ["Aether", "Lumine", "Chongyun", "Ganyu", "Hu Tao", "Kazuha", "Xiangling", "Yun Jin"]},
    { item: "Guide to Diligence", chars: ["Aether", "Lumine", "Chongyun", "Ganyu", "Hu Tao", "Kazuha", "Xiangling", "Yun Jin"]},
    { item: "Philosophies of Diligence", chars: ["Aether", "Lumine", "Chongyun", "Ganyu", "Hu Tao", "Kazuha", "Xiangling", "Yun Jin"]},
    { item: "Teachings of Gold", chars: ["Beidou", "Xingqiu", "Xinyan", "Yanfei", "Zhongli"]},
    { item: "Guide to Gold", chars: ["Aether", "Lumine", "Beidou", "Xingqiu", "Xinyan", "Yanfei", "Zhongli"]},
    { item: "Philosophies of Gold", chars: ["Aether", "Lumine", "Beidou", "Xingqiu", "Xinyan", "Yanfei", "Zhongli"]},
    { item: "Teachings of Transience", chars: ["Aether", "Lumine", "Kokomi", "Thoma", "Yoimiya"]},
    { item: "Guide to Transience", chars: ["Aether", "Lumine", "Kokomi", "Thoma", "Yoimiya"]},
    { item: "Philosophies of Transience", chars: ["Aether", "Lumine", "Kokomi", "Thoma", "Yoimiya"]},
    { item: "Teachings of Elegance", chars: ["Ayaka", "Itto", "Sara"]},
    { item: "Guide to Elegance", chars: ["Aether", "Lumine", "Ayaka", "Itto", "Sara"]},
    { item: "Philosophies of Elegance", chars: ["Aether", "Lumine", "Ayaka", "Itto", "Sara"]},
    { item: "Teachings of Light", chars: ["Gorou", "Raiden", "Sayu", "Yae Miko"]},
    { item: "Guide to Light", chars: ["Aether", "Lumine", "Gorou", "Raiden", "Sayu", "Yae Miko"]},
    { item: "Philosophies of Light", chars: ["Aether", "Lumine", "Gorou", "Raiden", "Sayu", "Yae Miko"]},
]

export const talBossMats = [
    { item: "Dvalin's Plume", chars: ["Bennett", "Diluc", "Jean"]},
    { item: "Dvalin's Claw", chars: ["Lisa", "Noelle", "Razor", "Xiangling"]},
    { item: "Dvalin's Sigh", chars: ["Aether", "Lumine", "Amber", "Beidou", "Chongyun"]},
    { item: "Tail of Boreas", chars: ["Aether", "Lumine", "Qiqi", "Venti", "Xingqiu"]},
    { item: "Ring of Boreas", chars: ["Barbara", "Keqing", "Klee", "Mona"]},
    { item: "Spirit Locket of Boreas", chars: ["Fischl", "Kaeya", "Ningguang", "Sucrose"]},
    { item: "Tusk of Monoceros Caeli", chars: ["Albedo", "Xinyan", "Zhongli"]},
    { item: "Shard of a Foul Legacy", chars: ["Diona", "Hu Tao", "Tartaglia"]},
    { item: "Shadow of the Warrior", chars: ["Ganyu", "Rosaria", "Xiao"]},
    { item: "Dragon Lord's Crown", chars: ["Aether", "Lumine", "Eula", "Yoimiya"]},
    { item: "Bloodjade Branch", chars: ["Ayaka", "Yanfei"]},
    { item: "Gilded Scale", chars: ["Kazuha", "Sayu"]},
    { item: "Molten Moment", chars: ["Aloy", "Gorou", "Raiden"]},
    { item: "Hellfire Butterfly", chars: ["Kokomi", "Shenhe", "Thoma"]},
    { item: "Ashen Heart", chars: ["Itto", "Sara", "Yun Jin"]},
    { item: "Mudra of the Malefic General", chars: []},
    { item: "Tears of the Calamitous God", chars: []},
    { item: "The Meaning of Aeons", chars: ["Yae Miko"]},
]