export let totalAscended = [
    { item: "Calla Lily", amount: 0 },
    { item: "Wolfhook", amount: 0 },
    { item: "Valberry", amount: 0 },
    { item: "Cecilia", amount: 0 },
    { item: "Windwheel Aster", amount: 0 },
    { item: "Philanemo Mushroom", amount: 0 },
    { item: "Jueyun Chili", amount: 0 },
    { item: "Noctilucous Jade", amount: 0 },
    { item: "Silk Flower", amount: 0 },
    { item: "Glaze Lily", amount: 0 },
    { item: "Qingxin", amount: 0 },
    { item: "Starconch", amount: 0 },
    { item: "Violetgrass", amount: 0 },
    { item: "Small Lamp Grass", amount: 0 },
    { item: "Dandelion Seed", amount: 0 },
    { item: "Cor Lapis", amount: 0 },
    { item: "Sea Ganoderma", amount: 0 },
    { item: "Fei Sakura Hydrangea", amount: 0 },
    { item: "Crystallized Bone Marrow", amount: 0 },
    { item: "Narussa", amount: 0 },
    { item: "Ghost Worm", amount: 0 },
    { item: "Dendrobrium", amount: 0 },
    { item: "Seagrass", amount: 0 },
    { item: "Violet Gourd", amount: 0 },
    { item: "Slime Condensate", amount: 0 },
    { item: "Slime Secretions", amount: 0 },
    { item: "Slime Concentrate", amount: 0 },
    { item: "Damaged Mask", amount: 0 },
    { item: "Stained Mask", amount: 0 },
    { item: "Ominous Mask", amount: 0 },
    { item: "Divining Scroll", amount: 0 },
    { item: "Sealed Scroll", amount: 0 },
    { item: "Forbidden Scroll", amount: 0 },
    { item: "Firm Arrowhead", amount: 0 },
    { item: "Sharp Arrowhead", amount: 0 },
    { item: "Weathered Arrowhead", amount: 0 },
    { item: "Recruit's Insignia", amount: 0 },
    { item: "Sergeant's Insignia", amount: 0 },
    { item: "Lieutenant's Insignia", amount: 0 },
    { item: "Treasure Hoarder Insignia", amount: 0 },
    { item: "Silver Raven Insignia", amount: 0 },
    { item: "Golden Raven Insignia", amount: 0 },
    { item: "Whopperflower Nectar", amount: 0 },
    { item: "Shimmering Nectar", amount: 0 },
    { item: "Energy Nectar", amount: 0 },
    { item: "Dilapidated Knife", amount: 0 },
    { item: "Tan Shadow Knife", amount: 0 },
    { item: "Famous Knife", amount: 0 },
    { item: "Everflame Seed", amount: 0 },
    { item: "Hoarfrost Core", amount: 0 },
    { item: "Cleansing Heart", amount: 0 },
    { item: "Hurricane Seed", amount: 0 },
    { item: "Lightning Prism", amount: 0 },
    { item: "Basalt Pillar", amount: 0 },
    { item: "Juvenile Jade", amount: 0 },
    { item: "Crystalline Bloom", amount: 0 },
    { item: "Marionnette Core", amount: 0 },
    { item: "The Heart of Constant Organ", amount: 0 },
    { item: "Smoldering Orb", amount: 0 },
    { item: "Agate Sliver", amount: 0 },
    { item: "Agate Fragment", amount: 0 },
    { item: "Agate Chunk", amount: 0 },
    { item: "Agate Gemstone", amount: 0 },
    { item: "Amethyst Sliver", amount: 0 },
    { item: "Amethyst Fragment", amount: 0 },
    { item: "Amethyst Chunk", amount: 0 },
    { item: "Amethyst Gemstone", amount: 0 },
    { item: "Lazurite Sliver", amount: 0 },
    { item: "Lazurite Fragment", amount: 0 },
    { item: "Lazurite Chunk", amount: 0 },
    { item: "Lazurite Gemstone", amount: 0 },
    { item: "Topaz Sliver", amount: 0 },
    { item: "Topaz Fragment", amount: 0 },
    { item: "Topaz Chunk", amount: 0 },
    { item: "Topaz Gemstone", amount: 0 },
    { item: "Jade Sliver", amount: 0 },
    { item: "Jade Fragment", amount: 0 },
    { item: "Jade Chunk", amount: 0 },
    { item: "Jade Gemstone", amount: 0 },
    { item: "Turquoise Sliver", amount: 0 },
    { item: "Turquoise Fragment", amount: 0 },
    { item: "Turquoise Chunk", amount: 0 },
    { item: "Turquoise Gemstone", amount: 0 },
    { item: "Brilliant Diamond Sliver", amount: 0 },
    { item: "Brilliant Diamond Fragment", amount: 0 },
    { item: "Brilliant Diamond Chunk", amount: 0 },
    { item: "Brilliant Diamond Gemstone", amount: 0 },
]

export let totalTalents = [
    { item: "Crown of Sagehood", amount: 0 },
    { item: "Dvalin's Plume", amount: 0 },
    { item: "Dvalin's Claw", amount: 0 },
    { item: "Dvalin's Sigh", amount: 0 },
    { item: "Tail of Boreas", amount: 0 },
    { item: "Ring of Boreas", amount: 0 },
    { item: "Spirit Locket of Boreas", amount: 0 },
    { item: "Tusk of Monoceros Caeli", amount: 0 },
    { item: "Shard of a Foul Legacy", amount: 0 },
    { item: "Shadow of the Warrior", amount: 0 },
    { item: "Bloodjade Branch", amount: 0 },
    { item: "Dragon Lord's Crown", amount: 0 },
    { item: "Gilded Scale", amount: 0 },
    { item: "Teachings of Freedom", amount: 0 },
    { item: "Guide to Freedom", amount: 0 },
    { item: "Philosophies of Freedom", amount: 0 },
    { item: "Teachings of Ballad", amount: 0 },
    { item: "Guide to Ballad", amount: 0 },
    { item: "Philosophies of Ballad", amount: 0 },
    { item: "Teachings of Resistance", amount: 0 },
    { item: "Guide to Resistance", amount: 0 },
    { item: "Philosophies of Resistance", amount: 0 },
    { item: "Teachings of Prosperity", amount: 0 },
    { item: "Guide to Prosperity", amount: 0 },
    { item: "Philosophies of Prosperity", amount: 0 },
    { item: "Teachings of Diligence", amount: 0 },
    { item: "Guide to Diligence", amount: 0 },
    { item: "Philosophies of Diligence", amount: 0 },
    { item: "Teachings of Gold", amount: 0 },
    { item: "Guide to Gold", amount: 0 },
    { item: "Philosophies of Gold", amount: 0 },
    { item: "Teachings of Uyiko", amount: 0 },
    { item: "Guide to Uyiko", amount: 0 },
    { item: "Philosophies of Uyiko", amount: 0 },
    { item: "Teachings of Elegance", amount: 0 },
    { item: "Guide to Elegance", amount: 0 },
    { item: "Philosophies of Elegance", amount: 0 },
    { item: "Teachings of Heavenly Light", amount: 0 },
    { item: "Guide to Heavenly Light", amount: 0 },
    { item: "Philosophies of Heavenly Light", amount: 0 },
]

export let totalOwned = [
    { item: "Calla Lily", amount: 0 },
    { item: "Wolfhook", amount: 0 },
    { item: "Valberry", amount: 0 },
    { item: "Cecilia", amount: 0 },
    { item: "Windwheel Aster", amount: 0 },
    { item: "Philanemo Mushroom", amount: 0 },
    { item: "Jueyun Chili", amount: 0 },
    { item: "Noctilucous Jade", amount: 0 },
    { item: "Silk Flower", amount: 0 },
    { item: "Glaze Lily", amount: 0 },
    { item: "Qingxin", amount: 0 },
    { item: "Starconch", amount: 0 },
    { item: "Violetgrass", amount: 0 },
    { item: "Small Lamp Grass", amount: 0 },
    { item: "Dandelion Seed", amount: 0 },
    { item: "Cor Lapis", amount: 0 },
    { item: "Sea Ganoderma", amount: 0 },
    { item: "Fei Sakura Hydrangea", amount: 0 },
    { item: "Crystallized Bone Marrow", amount: 0 },
    { item: "Narussa", amount: 0 },
    { item: "Ghost Worm", amount: 0 },
    { item: "Dendrobrium", amount: 0 },
    { item: "Seagrass", amount: 0 },
    { item: "Violet Gourd", amount: 0 },
    { item: "Slime Condensate", amount: 0 },
    { item: "Slime Secretions", amount: 0 },
    { item: "Slime Concentrate", amount: 0 },
    { item: "Damaged Mask", amount: 0 },
    { item: "Stained Mask", amount: 0 },
    { item: "Ominous Mask", amount: 0 },
    { item: "Divining Scroll", amount: 0 },
    { item: "Sealed Scroll", amount: 0 },
    { item: "Forbidden Scroll", amount: 0 },
    { item: "Firm Arrowhead", amount: 0 },
    { item: "Sharp Arrowhead", amount: 0 },
    { item: "Weathered Arrowhead", amount: 0 },
    { item: "Recruit's Insignia", amount: 0 },
    { item: "Sergeant's Insignia", amount: 0 },
    { item: "Lieutenant's Insignia", amount: 0 },
    { item: "Treasure Hoarder Insignia", amount: 0 },
    { item: "Silver Raven Insignia", amount: 0 },
    { item: "Golden Raven Insignia", amount: 0 },
    { item: "Whopperflower Nectar", amount: 0 },
    { item: "Shimmering Nectar", amount: 0 },
    { item: "Energy Nectar", amount: 0 },
    { item: "Dilapidated Knife", amount: 0 },
    { item: "Tan Shadow Knife", amount: 0 },
    { item: "Famous Knife", amount: 0 },
    { item: "Everflame Seed", amount: 0 },
    { item: "Hoarfrost Core", amount: 0 },
    { item: "Cleansing Heart", amount: 0 },
    { item: "Hurricane Seed", amount: 0 },
    { item: "Lightning Prism", amount: 0 },
    { item: "Basalt Pillar", amount: 0 },
    { item: "Juvenile Jade", amount: 0 },
    { item: "Crystalline Bloom", amount: 0 },
    { item: "Marionnette Core", amount: 0 },
    { item: "The Heart of Constant Organ", amount: 0 },
    { item: "Smoldering Orb", amount: 0 },
    { item: "Agate Sliver", amount: 0 },
    { item: "Agate Fragment", amount: 0 },
    { item: "Agate Chunk", amount: 0 },
    { item: "Agate Gemstone", amount: 0 },
    { item: "Amethyst Sliver", amount: 0 },
    { item: "Amethyst Fragment", amount: 0 },
    { item: "Amethyst Chunk", amount: 0 },
    { item: "Amethyst Gemstone", amount: 0 },
    { item: "Lazurite Sliver", amount: 0 },
    { item: "Lazurite Fragment", amount: 0 },
    { item: "Lazurite Chunk", amount: 0 },
    { item: "Lazurite Gemstone", amount: 0 },
    { item: "Topaz Sliver", amount: 0 },
    { item: "Topaz Fragment", amount: 0 },
    { item: "Topaz Chunk", amount: 0 },
    { item: "Topaz Gemstone", amount: 0 },
    { item: "Jade Sliver", amount: 0 },
    { item: "Jade Fragment", amount: 0 },
    { item: "Jade Chunk", amount: 0 },
    { item: "Jade Gemstone", amount: 0 },
    { item: "Turquoise Sliver", amount: 0 },
    { item: "Turquoise Fragment", amount: 0 },
    { item: "Turquoise Chunk", amount: 0 },
    { item: "Turquoise Gemstone", amount: 0 },
    { item: "Brilliant Diamond Sliver", amount: 0 },
    { item: "Brilliant Diamond Fragment", amount: 0 },
    { item: "Brilliant Diamond Chunk", amount: 0 },
    { item: "Brilliant Diamond Gemstone", amount: 0 },
    { item: "Crown of Sagehood", amount: 0 },
    { item: "Dvalin's Plume", amount: 0 },
    { item: "Dvalin's Claw", amount: 0 },
    { item: "Dvalin's Sigh", amount: 0 },
    { item: "Tail of Boreas", amount: 0 },
    { item: "Ring of Boreas", amount: 0 },
    { item: "Spirit Locket of Boreas", amount: 0 },
    { item: "Tusk of Monoceros Caeli", amount: 0 },
    { item: "Shard of a Foul Legacy", amount: 0 },
    { item: "Shadow of the Warrior", amount: 0 },
    { item: "Bloodjade Branch", amount: 0 },
    { item: "Dragon Lord's Crown", amount: 0 },
    { item: "Gilded Scale", amount: 0 },
    { item: "Teachings of Freedom", amount: 0 },
    { item: "Guide to Freedom", amount: 0 },
    { item: "Philosophies of Freedom", amount: 0 },
    { item: "Teachings of Ballad", amount: 0 },
    { item: "Guide to Ballad", amount: 0 },
    { item: "Philosophies of Ballad", amount: 0 },
    { item: "Teachings of Resistance", amount: 0 },
    { item: "Guide to Resistance", amount: 0 },
    { item: "Philosophies of Resistance", amount: 0 },
    { item: "Teachings of Prosperity", amount: 0 },
    { item: "Guide to Prosperity", amount: 0 },
    { item: "Philosophies of Prosperity", amount: 0 },
    { item: "Teachings of Diligence", amount: 0 },
    { item: "Guide to Diligence", amount: 0 },
    { item: "Philosophies of Diligence", amount: 0 },
    { item: "Teachings of Gold", amount: 0 },
    { item: "Guide to Gold", amount: 0 },
    { item: "Philosophies of Gold", amount: 0 },
    { item: "Teachings of Uyiko", amount: 0 },
    { item: "Guide to Uyiko", amount: 0 },
    { item: "Philosophies of Uyiko", amount: 0 },
    { item: "Teachings of Elegance", amount: 0 },
    { item: "Guide to Elegance", amount: 0 },
    { item: "Philosophies of Elegance", amount: 0 },
    { item: "Teachings of Heavenly Light", amount: 0 },
    { item: "Guide to Heavenly Light", amount: 0 },
    { item: "Philosophies of Heavenly Light", amount: 0 },
]