export let totalOwned = [
	{ item: "Calla Lily", amount: 0 },
	{ item: "Wolfhook", amount: 0 },
	{ item: "Valberry", amount: 0 },
	{ item: "Cecilia", amount: 0 },
	{ item: "Windwheel Aster", amount: 0 },
	{ item: "Philanemo Mushroom", amount: 0 },
	{ item: "Jueyun Chili", amount: 0 },
	{ item: "Noctilucous Jade", amount: 0 },
	{ item: "Silk Flower", amount: 0 },
	{ item: "Glaze Lily", amount: 0 },
	{ item: "Qingxin", amount: 0 },
	{ item: "Starconch", amount: 0 },
	{ item: "Violetgrass", amount: 0 },
	{ item: "Small Lamp Grass", amount: 0 },
	{ item: "Dandelion Seed", amount: 0 },
	{ item: "Cor Lapis", amount: 0 },
	{ item: "Onikabuto", amount: 0 },
	{ item: "Sakura Bloom", amount: 0 },
	{ item: "Crystal Marrow", amount: 0 },
	{ item: "Dendrobrium", amount: 0 },
	{ item: "Naku Weed", amount: 0 },
	{ item: "Sea Ganoderma", amount: 0 },
	{ item: "Sango Pearl", amount: 0 },
	{ item: "Amakumo Fruit", amount: 0 },
	{ item: "Fluorescent Fungus", amount: 0 },
	{ item: "Slime Condensate", amount: 0 },
	{ item: "Slime Secretions", amount: 0 },
	{ item: "Slime Concentrate", amount: 0 },
	{ item: "Damaged Mask", amount: 0 },
	{ item: "Stained Mask", amount: 0 },
	{ item: "Ominous Mask", amount: 0 },
	{ item: "Divining Scroll", amount: 0 },
	{ item: "Sealed Scroll", amount: 0 },
	{ item: "Forbidden Scroll", amount: 0 },
	{ item: "Firm Arrowhead", amount: 0 },
	{ item: "Sharp Arrowhead", amount: 0 },
	{ item: "Weathered Arrowhead", amount: 0 },
	{ item: "Recruit's Insignia", amount: 0 },
	{ item: "Sergeant's Insignia", amount: 0 },
	{ item: "Lieutenant's Insignia", amount: 0 },
	{ item: "Treasure Hoarder Insignia", amount: 0 },
	{ item: "Silver Raven Insignia", amount: 0 },
	{ item: "Golden Raven Insignia", amount: 0 },
	{ item: "Whopperflower Nectar", amount: 0 },
	{ item: "Shimmering Nectar", amount: 0 },
	{ item: "Energy Nectar", amount: 0 },
	{ item: "Old Handguard", amount: 0 },
	{ item: "Kageuchi Handguard", amount: 0 },
	{ item: "Famed Handguard", amount: 0 },
	{ item: "Spectral Husk", amount: 0 },
	{ item: "Spectral Heart", amount: 0 },
	{ item: "Spectral Nucleus", amount: 0 },
	{ item: "Hurricane Seed", amount: 0 },
	{ item: "Lightning Prism", amount: 0 },
	{ item: "Basalt Pillar", amount: 0 },
	{ item: "Hoarfrost Core", amount: 0 },
	{ item: "Everflame Seed", amount: 0 },
	{ item: "Cleansing Heart", amount: 0 },
	{ item: "Juvenile Jade", amount: 0 },
	{ item: "Crystalline Bloom", amount: 0 },
	{ item: "Marionette Core", amount: 0 },
	{ item: "Perpetual Heart", amount: 0 },
	{ item: "Smoldering Pearl", amount: 0 },
	{ item: "Storm Beads", amount: 0 },
	{ item: "Dew of Repudiation", amount: 0 },
	{ item: "Riftborn Regalia", amount: 0 },
	{ item: "Dragonheir's False Fin", amount: 0 },
	{ item: "Runic Fang", amount: 0 },
	{ item: "Agate Sliver", amount: 0 },
	{ item: "Agate Fragment", amount: 0 },
	{ item: "Agate Chunk", amount: 0 },
	{ item: "Agate Gemstone", amount: 0 },
	{ item: "Lazurite Sliver", amount: 0 },
	{ item: "Lazurite Fragment", amount: 0 },
	{ item: "Lazurite Chunk", amount: 0 },
	{ item: "Lazurite Gemstone", amount: 0 },
	{ item: "Amethyst Sliver", amount: 0 },
	{ item: "Amethyst Fragment", amount: 0 },
	{ item: "Amethyst Chunk", amount: 0 },
	{ item: "Amethyst Gemstone", amount: 0 },
	{ item: "Turquoise Sliver", amount: 0 },
	{ item: "Turquoise Fragment", amount: 0 },
	{ item: "Turquoise Chunk", amount: 0 },
	{ item: "Turquoise Gemstone", amount: 0 },
	{ item: "Jade Sliver", amount: 0 },
	{ item: "Jade Fragment", amount: 0 },
	{ item: "Jade Chunk", amount: 0 },
	{ item: "Jade Gemstone", amount: 0 },
	{ item: "Topaz Sliver", amount: 0 },
	{ item: "Topaz Fragment", amount: 0 },
	{ item: "Topaz Chunk", amount: 0 },
	{ item: "Topaz Gemstone", amount: 0 },
	// { item: "Emerald Sliver", amount: 0 },
	// { item: "Emerald Fragment", amount: 0 },
	// { item: "Emerald Chunk", amount: 0 },
	// { item: "Emerald Gemstone", amount: 0 },
	{ item: "Brilliant Diamond Sliver", amount: 0 },
	{ item: "Brilliant Diamond Fragment", amount: 0 },
	{ item: "Brilliant Diamond Chunk", amount: 0 },
	{ item: "Brilliant Diamond Gemstone", amount: 0 },
	{ item: "Crown of Sagehood", amount: 0 },
	{ item: "Dvalin's Plume", amount: 0 },
	{ item: "Dvalin's Claw", amount: 0 },
	{ item: "Dvalin's Sigh", amount: 0 },
	{ item: "Tail of Boreas", amount: 0 },
	{ item: "Ring of Boreas", amount: 0 },
	{ item: "Spirit Locket of Boreas", amount: 0 },
	{ item: "Tusk of Monoceros Caeli", amount: 0 },
	{ item: "Shard of a Foul Legacy", amount: 0 },
	{ item: "Shadow of the Warrior", amount: 0 },
	{ item: "Bloodjade Branch", amount: 0 },
	{ item: "Dragon Lord's Crown", amount: 0 },
	{ item: "Gilded Scale", amount: 0 },
	{ item: "Molten Moment", amount: 0 },
	{ item: "Hellfire Butterfly", amount: 0 },
	{ item: "Ashen Heart", amount: 0 },
	{ item: "Mudra of the Malefic General", amount: 0 },
	{ item: "Tears of the Calamitous God", amount: 0 },
	{ item: "The Meaning of Aeons", amount: 0 },
	{ item: "Teachings of Freedom", amount: 0 },
	{ item: "Guide to Freedom", amount: 0 },
	{ item: "Philosophies of Freedom", amount: 0 },
	{ item: "Teachings of Ballad", amount: 0 },
	{ item: "Guide to Ballad", amount: 0 },
	{ item: "Philosophies of Ballad", amount: 0 },
	{ item: "Teachings of Resistance", amount: 0 },
	{ item: "Guide to Resistance", amount: 0 },
	{ item: "Philosophies of Resistance", amount: 0 },
	{ item: "Teachings of Prosperity", amount: 0 },
	{ item: "Guide to Prosperity", amount: 0 },
	{ item: "Philosophies of Prosperity", amount: 0 },
	{ item: "Teachings of Diligence", amount: 0 },
	{ item: "Guide to Diligence", amount: 0 },
	{ item: "Philosophies of Diligence", amount: 0 },
	{ item: "Teachings of Gold", amount: 0 },
	{ item: "Guide to Gold", amount: 0 },
	{ item: "Philosophies of Gold", amount: 0 },
	{ item: "Teachings of Transience", amount: 0 },
	{ item: "Guide to Transience", amount: 0 },
	{ item: "Philosophies of Transience", amount: 0 },
	{ item: "Teachings of Elegance", amount: 0 },
	{ item: "Guide to Elegance", amount: 0 },
	{ item: "Philosophies of Elegance", amount: 0 },
	{ item: "Teachings of Light", amount: 0 },
	{ item: "Guide to Light", amount: 0 },
	{ item: "Philosophies of Light", amount: 0 },
]