export const travelerChar = [
	{ 
		name: "traveler",
		element: "anemo",
		ascension: 0,
		owned: false,
		fav: false,
		talent1: 1,
		talent2: 1,
		talent3: 1,
		properties: {
			ascension: { 
				twoStar: { item: "Brilliant Diamond Sliver", value: 0 },
				threeStar: { item: "Brilliant Diamond Fragment", value: 0 },
				fourStar: { item: "Brilliant Diamond Chunk", value: 0 },
				fiveStar: { item: "Brilliant Diamond Gemstone", value: 0 },
			},
			common: {
				oneStar: { item: "Damaged Mask", value: 0 },
				twoStar: { item: "Stained Mask", value: 0 },
				threeStar: { item: "Ominous Mask", value: 0 },
			},
			region: { item: "Windwheel Aster", value: 0 },
			crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
			talent: {
				twoStar: { item: "Teachings of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelThreeSix: { item: "Guide to Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelFour: { item: "Guide to Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelFive: { item: "Guide to Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelSevenTen: { item: "Philosophies of Ballad", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelEight: { item: "Philosophies of Freedom", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelNine: { item: "Philosophies of Resistance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			},
			talBoss: { item: "Dvalin's Sigh", value: { tal1: 0, tal2: 0, tal3: 0 }},
			talCommon: { 
				oneStar: { item: "Divining Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
				twoStar: { item: "Sealed Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
				threeStar: { item: "Forbidden Scroll", value: { tal1: 0, tal2: 0, tal3: 0 }},
			},
		}
	}, { 
		name: "traveler",
		element: "geo",
		ascension: 0,
		owned: false,
		fav: false,
		talent1: 1,
		talent2: 1,
		talent3: 1,
		properties: {
			ascension: { 
				twoStar: { item: "Brilliant Diamond Sliver", value: 0 },
				threeStar: { item: "Brilliant Diamond Fragment", value: 0 },
				fourStar: { item: "Brilliant Diamond Chunk", value: 0 },
				fiveStar: { item: "Brilliant Diamond Gemstone", value: 0 },
			},
			common: {
				oneStar: { item: "Damaged Mask", value: 0 },
				twoStar: { item: "Stained Mask", value: 0 },
				threeStar: { item: "Ominous Mask", value: 0 },
			},
			region: { item: "Windwheel Aster", value: 0 },
			crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
			talent: {
				twoStar: { item: "Teachings of Freedom", value: { tal1: 0 }},
				levelThreeSix: { item: "Guide to Resistance", value: { tal1: 0 }},
				levelFour: { item: "Guide to Ballad", value: { tal1: 0 }},
				levelFive: { item: "Guide to Freedom", value: { tal1: 0 }},
				levelSevenTen: { item: "Philosophies of Ballad", value: { tal1: 0 }},
				levelEight: { item: "Philosophies of Freedom", value: { tal1: 0 }},
				levelNine: { item: "Philosophies of Resistance", value: { tal1: 0 }},
			},
			talentGeo: {
				twoStar: { item: "Teachings of Prosperity", value: { tal2: 0, tal3: 0 }},
				levelThreeSix: { item: "Guide to Diligence", value: { tal2: 0, tal3: 0 }},
				levelFour: { item: "Guide to Gold", value: { tal2: 0, tal3: 0 }},
				levelFive: { item: "Guide to Prosperity", value: { tal2: 0, tal3: 0 }},
				levelSevenTen: { item: "Philosophies of Gold", value: { tal2: 0, tal3: 0 }},
				levelEight: { item: "Philosophies of Prosperity", value: { tal2: 0, tal3: 0 }},
				levelNine: { item: "Philosophies of Diligence", value: { tal2: 0, tal3: 0 }},
			},
			talBoss: { item: "Dvalin's Sigh", value: { tal1: 0 }},
			talBossGeo: { item: "Tail of Boreas", value: { tal2: 0, tal3: 0 }},
			talCommon: { 
				oneStar: { item: "Divining Scroll", value: { tal1: 0 }},
				twoStar: { item: "Sealed Scroll", value: { tal1: 0 }},
				threeStar: { item: "Forbidden Scroll", value: { tal1: 0 }},
			},
			talCommonGeo: { 
				oneStar: { item: "Firm Arrowhead", value: { tal2: 0, tal3: 0 }},
				twoStar: { item: "Sharp Arrowhead", value: { tal2: 0, tal3: 0 }},
				threeStar: { item: "Weathered Arrowhead", value: { tal2: 0, tal3: 0 }},
			},
		}
	},{ 
		name: "traveler",
		element: "electro",
		ascension: 0,
		owned: false,
		fav: false,
		talent1: 1,
		talent2: 1,
		talent3: 1,
		properties: {
			ascension: { 
				twoStar: { item: "Brilliant Diamond Sliver", value: 0 },
				threeStar: { item: "Brilliant Diamond Fragment", value: 0 },
				fourStar: { item: "Brilliant Diamond Chunk", value: 0 },
				fiveStar: { item: "Brilliant Diamond Gemstone", value: 0 },
			},
			common: {
				oneStar: { item: "Damaged Mask", value: 0 },
				twoStar: { item: "Stained Mask", value: 0 },
				threeStar: { item: "Ominous Mask", value: 0 },
			},
			region: { item: "Windwheel Aster", value: 0 },
			crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
			talent: {
				twoStar: { item: "Teachings of Transience", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelThreeSix: { item: "Guide to Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelFour: { item: "Guide to Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelFive: { item: "Guide to Transience", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelSevenTen: { item: "Philosophies of Light", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelEight: { item: "Philosophies of Transience", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelNine: { item: "Philosophies of Elegance", value: { tal1: 0, tal2: 0, tal3: 0 }},
			},
			talBoss: { item: "Dragon Lord's Crown", value: { tal1: 0, tal2: 0, tal3: 0 }},
			talCommon: { 
				oneStar: { item: "Old Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
				twoStar: { item: "Kageuchi Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
				threeStar: { item: "Famed Handguard", value: { tal1: 0, tal2: 0, tal3: 0 }},
			},
		}
	},{ 
		name: "traveler",
		element: "dendro",
		ascension: 0,
		owned: false,
		fav: false,
		talent1: 1,
		talent2: 1,
		talent3: 1,
		properties: {
			ascension: { 
				twoStar: { item: "Brilliant Diamond Sliver", value: 0 },
				threeStar: { item: "Brilliant Diamond Fragment", value: 0 },
				fourStar: { item: "Brilliant Diamond Chunk", value: 0 },
				fiveStar: { item: "Brilliant Diamond Gemstone", value: 0 },
			},
			common: {
				oneStar: { item: "Damaged Mask", value: 0 },
				twoStar: { item: "Stained Mask", value: 0 },
				threeStar: { item: "Ominous Mask", value: 0 },
			},
			region: { item: "Windwheel Aster", value: 0 },
			crown: { item: "Crown of Sagehood", value: { tal1: 0, tal2: 0, tal3: 0 }},
			talent: {
				twoStar: { item: "Teachings of Admonition", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelThreeSix: { item: "Guide to Ingenuity", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelFour: { item: "Guide to Praxis", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelFive: { item: "Guide to Admonition", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelSevenTen: { item: "Philosophies of Praxis", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelEight: { item: "Philosophies of Admonition", value: { tal1: 0, tal2: 0, tal3: 0 }},
				levelNine: { item: "Philosophies of Ingenuity", value: { tal1: 0, tal2: 0, tal3: 0 }},
			},
			talBoss: { item: "Mudra of the Malefic General", value: { tal1: 0, tal2: 0, tal3: 0 }},
			talCommon: { 
				oneStar: { item: "Fungal Spores", value: { tal1: 0, tal2: 0, tal3: 0 }},
				twoStar: { item: "Luminescent Pollen", value: { tal1: 0, tal2: 0, tal3: 0 }},
				threeStar: { item: "Crystalline Cyst Dust", value: { tal1: 0, tal2: 0, tal3: 0 }},
			},
		}
	},
]